/**
 * @file     cmp.h (180.ARM_Peripherals/Project_Headers/cmp.h)
 * @brief    Analogue Comparator
 */

#ifndef HEADER_CMP_H_
#define HEADER_CMP_H_

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "derivative.h"
#include "pin_mapping.h"

namespace USBDM {

/**
 * @addtogroup CMP_Group CMP, Analogue Comparator
 * @brief Pins used for Analogue Comparator
 * @{
 */

$(/CMP/peripheral_h_definition:// $/CMP/peripheral_h_definition not found)
$(/CMP/InputMapping:   // /CMP/InputMapping None Found)
$(/CMP/declarations:   // /CMP/declarations None Found)

/**
 * End CMP_Group
 * @}
 */
} // End namespace USBDM

#endif /* HEADER_CMP_H_ */
