/**
 * @file      ics.h (180.ARM_Peripherals/Project_Headers/ics.h)
 *
 * @brief    Abstraction layer for ICS interface
 *
 * @version  V4.12.1.80
 * @date     13 April 2016
 */
 
#ifndef INCLUDE_USBDM_ICS_H_
#define INCLUDE_USBDM_ICS_H_
 /*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "derivative.h"
#include "system.h"
#include "pin_mapping.h"

namespace USBDM {

/**
 * @addtogroup ICS_Group ICS, Multipurpose Clock Generator
 * @brief Abstraction for Multipurpose Clock Generator
 * @{
 */

/**
 * Clock configurations
 */
enum ClockConfig : uint8_t {
$(/ICS/ClockConfig: #error ClockConfig not found)
   ClockConfig_default = 0,
};

$(/ICS/ClockInfoType:#error ClockInfoType not found)

class ClockChangeCallback {

friend class Ics;

private:
      // Pointer to next in chain
      ClockChangeCallback *next = nullptr;

public:
      virtual ~ClockChangeCallback() = default;

      /**
       * This method is overridden to obtain notification before clock change
       */
      virtual void beforeClockChange(){}

      /**
       * This method is overridden to obtain notification after clock change
       */
      virtual void afterClockChange(){};
};

/**
 * @brief Class representing the ICS
 *
 * <b>Example</b>
 * @code
 *    Ics::initialise();
 * @endcode
 */
class Ics : public IcsInfo {

private:
#if $(/ICS/enableClockChangeNotifications:false)
   static ClockChangeCallback *clockChangeCallbackQueue;

   static void notifyBeforeClockChange() {
      ClockChangeCallback *p = clockChangeCallbackQueue;
      while (p != nullptr) {
         p->beforeClockChange();
         p = p->next;
      }
   }
   static void notifyAfterClockChange() {
      ClockChangeCallback *p = clockChangeCallbackQueue;
      while (p != nullptr) {
         p->afterClockChange();
         p = p->next;
      }
   }

public:
   /**
    * Add callback for clock configuration changes
    *
    * @param callback Call-back class to notify on clock configuration changes
    */
   static void addClockChangeCallback(ClockChangeCallback &callback) {
      callback.next = clockChangeCallbackQueue;
      clockChangeCallbackQueue = &callback;
   }
#endif

private:
   /** Hardware instance */
   static constexpr HardwarePtr<ICS_Type> ics = IcsInfo::baseAddress;

$(/ICS/privateMethods: // No private methods found)

public:

$(/ICS/publicMethods: // No public methods found)

   /**
    * Table of clock settings
    */
   static const ClockInfo clockInfo[];

   /**
    * Enable interrupts in NVIC
    */
   static void enableNvicInterrupts() {
      NVIC_EnableIRQ(IcsInfo::irqNums[0]);
   }

   /**
    * Enable and set priority of interrupts in NVIC
    * Any pending NVIC interrupts are first cleared.
    *
    * @param[in]  nvicPriority  Interrupt priority
    */
   static void enableNvicInterrupts(NvicPriority nvicPriority) {
      enableNvicInterrupt(IcsInfo::irqNums[0], nvicPriority);
   }

   /**
    * Disable interrupts in NVIC
    */
   static void disableNvicInterrupts() {
      NVIC_DisableIRQ(IcsInfo::irqNums[0]);
   }
   
   /** Current clock mode (FEI out of reset) */
   static IcsClockMode currentClockMode;

   /**
    * Update SystemCoreClock variable
    *
    * Updates the SystemCoreClock variable with current core Clock retrieved from CPU registers.
    */
   static void SystemCoreClockUpdate(void);

#if $(/ICS/enablePeripheralSupport:false) // /ICS/enablePeripheralSupport

   /**
    * Transition from current clock mode to mode given
    *
    * @param[in]  clockInfo Clock mode to transition to
    *
    * @return E_NO_ERROR          on success
    * @return E_CLOCK_INIT_FAILED on failure
    */
   static ErrorCode clockTransition(const ClockInfo &clockInfo);

   /**
    * Get current clock mode
    *
    * @return
    */
   static IcsClockMode getClockMode() {
      return currentClockMode;
   }

   /**
    * Get name for clock mode
    *
    * @return Pointer to static string
    */
   static const char *getClockModeName(IcsClockMode);

   /**
    * Get name for current clock mode
    *
    * @return Pointer to static string
    */
   static const char *getClockModeName() {
      return getClockModeName(getClockMode());
   }

   /**
    *  Configure the ICS for given mode
    *
    *  @param[in]  settingNumber Clock setting number
    */
   static void configure(ClockConfig settingNumber=ClockConfig_default) {
      clockTransition(clockInfo[settingNumber]);
   }

   /**
    *   Finalise the ICS 
    */
   static void finalise() {
      clockTransition(clockInfo[ClockConfig_default]);
   }

#endif

   /**
    * Initialise ICS as part of startup sequence
    */
   static void startupConfigure();

$(/ICS/InitMethod: // No /ICS/InitMethod methods found)
};

$(/ICS/declarations: // /ICS/No declarations methods found)

/**
 * @}
 */

} // End namespace USBDM

#endif /* INCLUDE_USBDM_ICS_H_ */
