/**
 * @file     llwu.h (180.ARM_Peripherals/Project_Headers/llwu.h)
 * @brief    Low leakage wake-up unit
 */

#ifndef HEADER_LLWU_H
#define HEADER_LLWU_H

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "pin_mapping.h"

namespace USBDM {

#if $(/LLWU/_BasicInfoGuard) // /LLWU/_BasicInfoGuard

/**
 * @addtogroup LLWU_Group LLWU, Low-leakage Wake-up Unit
 * @brief Abstraction for Low-leakage Wake-up Unit
 * @{
 */
$(/LLWU/peripheral_h_definition:// $/MCM/peripheral_h_definition not found)
$(/LLWU/declarations: // No declarations found)
/**
 * End LLWU_Group
 * @}
 */
#endif // /LLWU/_BasicInfoGuard
} // End namespace USBDM

#endif /* HEADER_LLWU_H */
