/**
 * @file     trng.h (180.ARM_Peripherals/Project_Headers/trng.h)
 * @brief    True Random Number Generator
 */

#ifndef HEADER_TRNG_H_
#define HEADER_TRNG_H_

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "derivative.h"
#include "pin_mapping.h"


$(/TRNG/prototypes:// $/TRNG/prototypes not found)

namespace USBDM {

/**
 * @addtogroup TRNG_Group TRNG, Random Number Generator Accelerator
 * @brief Abstraction for Random Number Generator Accelerator
 * @{
 */
$(/TRNG/peripheral_h_definition:// $/TRNG/peripheral_h_definition not found)

$(/TRNG/declarations: // No declarations found)
/**
 * End TRNG_Group
 * @}
 */
} // End namespace USBDM

#endif /* HEADER_TRNG_H_ */
