/****************************************************************************************************//**
 * @file     uart.h (180.ARM_Peripherals/Project_Headers/uart.h)
 * @brief    Universal Asynchronous Receiver/Transmitter interface
 *
 * @version  V0.0
 * @date     2015/06
 *
 *******************************************************************************************************/

#ifndef INCLUDE_USBDM_UART_H_
#define INCLUDE_USBDM_UART_H_
 /*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include <stdint.h>
#include <cstdio>
#include "derivative.h"
#include "hardware.h"
#include "mcg.h"
#include "ctype.h"

namespace USBDM {

/**
 * @addtogroup UART_Group UART, Universal Asynchronous Receiver/Transmitter
 * @brief C++ Class allowing access to UART interface
 * @{
 */

/**
 * Enumeration selecting interrupt sources
 */
enum UartInterrupt {
   UartInterrupt_TxHoldingEmpty  = UART_C2_TIE(1),   //!< Interrupt request on Transmit holding register empty
   UartInterrupt_TxComplete      = UART_C2_TCIE(1),  //!< Interrupt request on Transmit complete
   UartInterrupt_RxFull          = UART_C2_RIE(1),   //!< Interrupt request on Receive holding full
   UartInterrupt_IdleDetect      = UART_C2_ILIE(1),  //!< Interrupt request on Idle detection
};

enum Radix {
   Radix_2  = 2,   //!< Convert as binary number
   Radix_8  = 8,   //!< Convert as octal number
   Radix_10 = 10,  //!< Convert as decimal number
   Radix_16 = 16,  //!< Convert as hexadecimal number
};

enum WhiteSpaceType {
   /**
    * With operator<< Discard input white-space characters
    */
   WhiteSpace
};

enum EndOfLineType  {
   /**
    * With operator<< Discard input until end-of-line \n
    * With operator>> Write end-of-line
    */
   EndOfLine
};

/**
 * Enumeration selecting direct memory access sources
 */
enum UartDma {
#ifdef UART_C5_TDMAS
   UartDma_TxHoldingEmpty  = UART_C5_TDMAS(1),   //!< DMA request on Transmit holding register empty
   UartDma_RxFull          = UART_C5_RDMAS(1),   //!< DMA request on Receive holding full
#endif
#ifdef UART_C5_TDMAE
   UartDma_TxHoldingEmpty  = UART_C5_TDMAE(1),   //!< DMA request on Transmit holding register empty
   UartDma_RxFull          = UART_C5_RDMAE(1),   //!< DMA request on Receive holding full
#endif
};

/**
 * Virtual Base class for UART interface
 */
class Uart {

public:

   volatile UART_Type * const uart;            //!< UART hardware instance

protected:
   /**
    * Current radix for << and >> operators
    */
   Radix fRadix = Radix_10;
   /**
    * One character look-ahead
    */
   int   lookAhead = -1;

   /**
    * Indicate in error state
    */
   bool inErrorState = false;

   virtual ~Uart() {}

   /**
    * Construct UART interface
    *
    * @param[in]  uart             Base address of UART hardware
    */
   Uart(volatile UART_Type *uart) : uart(uart) {
   }

   /**
    * Set baud factor value for interface
    *
    * This is calculated from baud rate and UART clock frequency
    *
    * @param[in]  baudrate       Interface speed in bits-per-second
    * @param[in]  clockFrequency Frequency of UART clock
    */
   void __attribute__((noinline)) setBaudRate(uint32_t baudrate, uint32_t clockFrequency) {

      // Disable UART before changing registers
      uart->C2 &= ~(UART_C2_TE_MASK | UART_C2_RE_MASK);

      // Calculate UART clock setting (5-bit fraction at right)
      int scaledBaudValue = (2*clockFrequency)/baudrate;

#ifdef UART_C4_BRFA_MASK
      // Set Baud rate register
      uart->BDH = (uart->BDH&~UART_BDH_SBR_MASK) | UART_BDH_SBR((scaledBaudValue>>(8+5)));
      uart->BDL = UART_BDL_SBR(scaledBaudValue>>5);
      // Fractional divider to get closer to the baud rate
      uart->C4 = (uart->C4&~UART_C4_BRFA_MASK) | UART_C4_BRFA(scaledBaudValue);
#else
      scaledBaudValue += 1<<4; // Round value
      // Set Baud rate register
      uart->BDH = (uart->BDH&~UART_BDH_SBR_MASK) | UART_BDH_SBR((scaledBaudValue>>(8+5)));
      uart->BDL = UART_BDL_SBR(scaledBaudValue>>5);
#endif

      uart->C1 = 0;

#if USE_IRQ
      // Enable UART Tx & Rx - with Rx IRQ
      uart->C2 = UART_C2_TE_MASK|UART_C2_RE_MASK|UART_C2_RIE_MASK;
#else
      // Enable UART Tx & Rx
      uart->C2 = UART_C2_TE_MASK|UART_C2_RE_MASK;
#endif
   }

   /**
    * Set baud factor value for interface
    *
    * This is calculated from baud rate and LPUART clock frequency
    *
    * @param[in]  baudrate  Interface speed in bits-per-second
    */
   virtual void setBaudRate(unsigned baudrate) = 0;

   /**
    * Convert character to digit in given radix
    *
    * @param[in] ch    The character to convert
    * @param[in] radix The radix to use
    *
    * @return >=0 Digit in range 0 - (radix-1)
    * @return <0  Invalid character for radix
    */
   static int convertDigit(int ch, Radix radix) {
      unsigned digit = ch - '0';
      if (digit<10) {
         return (digit<radix)?digit:-1;
      }
      digit = ch-'a'+10;
      if (digit<radix) {
         return digit;
      }
      digit = ch-'A'+10;
      if (digit<radix) {
         return digit;
      }
      return -1;
   }

public:
   /**
    * Converts an unsigned long to a string
    *
    * @param[in] value Unsigned long to convert
    * @param[in] ptr   Buffer to write result (at least 12 characters)
    * @param[in] radix Radix for conversion [2..16]
    *
    * @return Pointer to '\0' null character at end of converted number\n
    *         May be used for incrementally writing to a buffer.
    */
   static __attribute__((noinline)) char *ultoa(unsigned long value, char *ptr, Radix radix=Radix_10) {
#ifdef DEBUG_BUILD
      if (ptr == nullptr) {
         __BKPT();
      }
      if ((radix<2)||(radix>16)) {
         __BKPT();
      }
#endif
      // Save beginning for reversal
      char *beginPtr = ptr;
      // Convert backwards
      do {
         *ptr++ = "0123456789ABCDEF"[value % radix];
         value /= radix;
      } while (value != 0);
      // Terminate and leave ptr at last digit
      *ptr = '\0';
      // Reverse digits
      char *endPtr = ptr-1;
      while (beginPtr < endPtr) {
         char t = *beginPtr;
         *beginPtr++ = *endPtr;
         *endPtr-- = t;
      }
      return ptr;
   }

   /**
    * Converts a long to a string
    *
    * @param[in] value Long to convert
    * @param[in] ptr   Buffer to write result (at least 12 characters)
    * @param[in] radix Radix for conversion [2..16]
    *
    * @return Pointer to '\0' null character at end of converted number\n
    *         May be used for incrementally writing to a buffer.
    */
   static INLINE_RELEASE char *ltoa(long value, char *ptr, Radix radix=Radix_10) {
      if (value<0) {
         *ptr++ = '-';
         value = -value;
      }
      return ultoa(value, ptr, radix);
   }

   /**
    * Copies a C string including terminating '\0' character
    *
    * @param[out] dst  Where to copy string
    * @param[in]  src  Source to copy from
    *
    * @return Pointer to '\0' null character at end of converted number\n
    *         May be used for incrementally writing to a buffer.
    */
   static __attribute__((noinline)) char *strcpy(char *dst, const char *src) {
#ifdef DEBUG_BUILD
      if (dst == nullptr) {
         __BKPT();
      }
#endif
      do {
         *dst++ = *src;
      } while (*src++ != '\0');
      return dst-1;
   }

   /**
    * Transmit data
    *
    * @param[in]  data     Data to transmit
    * @param[in]  size     Size of transmission data
    */
   void transmit(const uint8_t data[], uint16_t size) {
      while (size-->0) {
         write(*data++);
      }
   }

   /**
    * Receive data
    *
    * @param[out] data     Data buffer for reception
    * @param[in]  size     Size of data to receive
    */
   void receive(uint8_t data[], uint16_t size) {
      while (size-->0) {
         *data++ = readChar();
      }
   }

   /**
    * Receive string until terminator character\n
    * The terminating character is discarded and the string '\0' terminated
    *
    * @param[out] data       Data buffer for reception
    * @param[in]  size       Size of data buffer (including '\0')
    * @param[in]  terminator Terminating character
    *
    * @return number of characters read (excluding terminator)
    *
    * Usage
    * @code
    *    char buff[100];
    *    int numChars = gets(buff, sizeof(buff));
    * @endcode
    */
   int gets(char data[], uint16_t size, char terminator='\n') {
      char *ptr = data;
      while (size-->1) {
         char ch = readChar();
         if (ch == terminator) {
            break;
         }
         *ptr++ = ch;
      }
      *ptr = '\0';
      return ptr-data;
   }

   /**
    * Push a value to the look-ahead buffer
    *
    * @param[in] ch Character to push
    */
   void __attribute__((always_inline)) pushBack(char ch) {
      lookAhead = (uint8_t)ch;
   }

   /**
    * Check if character is available from UART
    *
    * @return true  Character available i.e. readChar() will not block
    * @return false No character available
    */
   bool INLINE_RELEASE isCharAvailable() {
      return (lookAhead>0) || (uart->S1 & UART_S1_RDRF_MASK);
   }

   /**
    * Peek at UART buffer.
    * This routine supports a 1-character lookahead
    *
    * @return <0   No character available
    * @return >=0  Character available from UART
    *
    * @note This may trigger reading a character from the UART buffer, clearing flags etc.
    */
   int __attribute__((noinline)) peek() {
      if (lookAhead>0) {
         return lookAhead;
      }
      // Get status from UART
      uint8_t status = uart->S1;

      // Clear & ignore pending errors
      if ((status & (UART_S1_FE_MASK|UART_S1_OR_MASK|UART_S1_PF_MASK|UART_S1_NF_MASK)) != 0) {
         clearError();
      }
      // Check for Rx buffer full
      if ((status & UART_S1_RDRF_MASK) == 0) {
         // No char available
         return -1;
      }
      // Save as current lookahead
      pushBack(uart->D);
      if (lookAhead == (uint8_t)'\r') {
         pushBack('\n');
      }
      return lookAhead;
   }

   /**
    * Transmit a character
    *
    * @param[in]  ch - character to send
    *
    * @return Reference to the Uart
    */
   Uart __attribute__((noinline)) &write(char ch) {
      while ((uart->S1 & UART_S1_TDRE_MASK) == 0) {
         // Wait for Tx buffer empty
         __asm__("nop");
      }
      uart->D = ch;
      if (ch=='\n') {
         write('\r');
      }
      return *this;
   }

   /**
    * Transmit an end-of-line
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln() {
      return write('\n');
   }

   /**
    * Transmit a character with newline
    *
    * @param[in]  ch - character to send
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(char ch) {
      write(ch);
      return write('\n');
   }

   /**
    * Transmit a C string
    *
    * @param[in]  str String to print
    *
    * @return Reference to the Uart
    */
   Uart &write(const char *str) {
      while (*str != '\0') {
         write(*str++);
      }
      return *this;
   }

   /**
    * Transmit a C string with new line
    *
    * @param[in]  str String to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(const char *str) {
      write(str);
      return write('\n');
   }

   /**
    * Transmit a boolean value
    *
    * @param[in]  b Boolean to print
    *
    * @return Reference to the Uart
    */
   Uart &write(bool b) {
      return write(b?"true":"false");
   }

   /**
    * Transmit a boolean value with new line
    *
    * @param[in]  b Boolean to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(bool b) {
      write(b);
      return write('\n');
   }

   /**
    * Transmit an unsigned long integer
    *
    * @param[in]  value Unsigned long to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart __attribute__((noinline)) &write(unsigned long value, Radix radix=Radix_10) {
      static char buff[35];
      ultoa(value, buff, radix);
      return write(buff);
   }

   /**
    * Transmit an unsigned long integer with newline
    *
    * @param[in]  value Unsigned long to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(unsigned long value, Radix radix=Radix_10) {
      write(value, radix);
      return write('\n');
   }

   /**
    * Transmit a long integer
    *
    * @param[in]  value Long to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &write(long value, Radix radix=Radix_10) {
      if (value<0) {
         write('-');
         value = -value;
      }
      return write((unsigned long) value, radix);
   }

   /**
    * Transmit a long integer with newline
    *
    * @param[in]  value Long to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(long value, Radix radix=Radix_10) {
      write(value, radix);
      return write('\n');
   }

   /**
    * Transmit an unsigned integer
    *
    * @param[in]  value Unsigned to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &write(unsigned value, Radix radix=Radix_10) {
      return write((unsigned long)value, radix);
   }

   /**
    * Transmit an unsigned integer with newline
    *
    * @param[in]  value Unsigned to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &writeln(unsigned value, Radix radix=Radix_10) {
      return writeln((unsigned long)value, radix);
   }

   /**
    * Transmit an integer
    *
    * @param[in]  value Integer to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &write(int value, Radix radix=Radix_10) {
      return write((long)value, radix);
   }

   /**
    * Transmit an integer with newline
    *
    * @param[in]  value Integer to print
    * @param[in]  radix Radix for conversion [2..16]
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE  &writeln(int value, Radix radix=Radix_10) {
      return writeln((long)value, radix);
   }

   /**
    * Transmit a double
    *
    * @param[in]  value Double to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float)).
    */
   Uart &write(double value) {
      char buff[20];
      snprintf(buff, sizeof(buff), "%f", value);
      return write(buff);
   }

   /**
    * Transmit a double with newline
    *
    * @param[in]  value Double to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float).
    */
   Uart INLINE_RELEASE &writeln(double value) {
      write(value);
      return write('\n');
   }

   /**
    * Transmit a float
    *
    * @param[in]  value Float to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float).
    */
   Uart INLINE_RELEASE &write(float value) {
      return write((double)value);
   }

   /**
    * Transmit a float with newline
    *
    * @param[in]  value Float to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float)).
    */
   Uart INLINE_RELEASE &writeln(float value) {
      return writeln((double)value);
   }

   /**
    * Transmit a character
    *
    * @param[in]  ch Character to print
    *
    * @return Reference to the Uart
     */
   Uart INLINE_RELEASE &operator <<(char ch) {
      return write(ch);
   }

   /**
    * Transmit a boolean value
    *
    * @param[in]  b Boolean to print
    *
    * @return Reference to the Uart
     */
   Uart INLINE_RELEASE &operator <<(bool b) {
      return write(b);
   }

   /**
    * Transmit a C string
    *
    * @param[in]  str String to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(const char *str) {
      return write(str);
   }

   /**
    * Transmit an unsigned long integer
    *
    * @param[in]  value Unsigned long to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(unsigned long value) {
      return write(value, fRadix);
   }

   /**
    * Transmit a long integer
    *
    * @param[in]  value Long to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(long value) {
      return write(value, fRadix);
   }

   /**
    * Transmit an unsigned integer
    *
    * @param[in]  value Unsigned to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(unsigned int value) {
      return write(value, fRadix);
   }

   /**
    * Transmit an integer
    *
    * @param[in]  value Integer to print
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(int value) {
      return write(value, fRadix);
   }

   /**
    * Transmit a float
    *
    * @param[in]  value Float to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float)).
    */
   Uart INLINE_RELEASE &operator <<(float value) {
      return write((double)value);
   }

   /**
    * Transmit a double
    *
    * @param[in]  value Double to print
    *
    * @return Reference to the Uart
    *
    * @note Uses snprintf() which is large.
    * @note To use this function it is necessary to enable floating point printing\n
    *       in the linker options (Support %f format in printf -u _print_float)).
    */
   Uart INLINE_RELEASE &operator <<(double value) {
      return write(value);
   }

   /**
    * Sets the conversion radix for integer types
    *
    * @param[in] radix Radix to set
    *
    * @return Reference to the Uart
    *
    * @note Only applies for operator<< methods
    */
   Uart INLINE_RELEASE &operator <<(Radix radix) {
      fRadix = radix;
      return *this;
   }

   /**
    * Write end-of-line
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator <<(EndOfLineType) {
      write('\n');
      return *this;
   }

   /**
    * Receives a single character
    *
    * @return Character received
    */
   int __attribute__((noinline)) readChar(void) {
      int ch;
      do {
         ch = peek();
      } while (ch < 0);
      lookAhead = -1;
      return ch;
   }

   /**
    * Discard white-space from the input
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &skipWhiteSpace() {
      int ch;
      do {
         ch = readChar();
      } while (isspace(ch));
      pushBack(ch);
      return *this;
   }

   /**
    * Discard input until end-of-line (inclusive)
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &readln() {
      while (readChar() != '\n') {
         __asm__("nop");
      }
      return *this;
   }

   /**
    * Read a character from the input
    *
    * @param[out] ch Where to place character read
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &read(char &ch) {
      ch = readChar();
      return *this;
   }

   /**
    * Get and clear error state
    *
    * @return true  No error
    * @return false Last operation failed e.g. illegal digit at start of number
    */
   bool isOk() {
      bool t = inErrorState;
      inErrorState = false;
      return !t;
   }

   /**
    * Receives an unsigned long
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart &read(unsigned long &value, Radix radix=Radix_10) {
      // Skip white space
      int ch;
      do {
         ch = readChar();
      } while (isspace(ch));

      // Check if sign character
      bool negative = (ch == '-');
      if (negative) {
         // Discard  '-'
         ch = readChar();
      }

      // Parse number
      // Must have at least 1 digit
      int  digit   = convertDigit(ch, radix);
      inErrorState = (digit<0);

      value = 0;
      while (digit>=0) {
         value *= radix;
         value += digit;
         ch = readChar();
         digit = convertDigit(ch, radix);
      }
      // Push back 1st non-digit
      pushBack(ch);
      if (negative) {
         value = -value;
      }
      return *this;
   }

   /**
    * Receives an unsigned long and then discards characters until end of line.
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &readln(unsigned long &value, Radix radix=Radix_10) {
      read(value, radix);
      return readln();
   }

   /**
    * Receives a long
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart &read(long &value, Radix radix=Radix_10) {
      unsigned long temp;
      read(temp, radix);
      value = temp;
      return *this;
   }

   /**
    * Receives a long and then discards characters until end of line.
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &readln(long &value, Radix radix=Radix_10) {
      read(value, radix);
      return readln();
   }

   /**
    * Receives an unsigned integer
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart &read(unsigned int &value, Radix radix=Radix_10) {
      unsigned long temp;
      read(temp, radix);
      value = temp;
      return *this;
   }

   /**
    * Receives an unsigned integer and then discards characters until end of line.
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &readln(unsigned &value, Radix radix=Radix_10) {
      read(value, radix);
      return readln();
   }

   /**
    * Receives an integer
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart &read(int &value, Radix radix=Radix_10) {
      long temp;
      read(temp, radix);
      value = temp;
      return *this;
   }

   /**
    * Receives an integer and then discards characters until end of line.
    *
    * @param[out] value Where to place value read
    * @param[in]  radix The radix to use
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &readln(int &value, Radix radix=Radix_10) {
      read(value, radix);
      return readln();
   }

   /**
    * Discard white-space from the input
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator >>(WhiteSpaceType) {
      return skipWhiteSpace();
   }

   /**
    * Discard input until end-of-line
    *
    * @return Reference to the Uart
    */
   Uart &operator >>(EndOfLineType) {
      while (readChar() != '\n') {
         __asm__("nop");
      }
      return *this;
   }

   /**
    * Sets the conversion radix for integer types
    *
    * @param[in]  radix Radix to set
    *
    * @return Reference to the Uart
    *
    * @note Only applies for operator<< methods
    */
   Uart INLINE_RELEASE &operator >>(Radix radix) {
      fRadix = radix;
      return *this;
   }

   /**
    * Receives a single character
    *
    * @param[out] ch Where to place character read
    *
    * @return Reference to the Uart
    */
   Uart INLINE_RELEASE &operator >>(char &ch) {
      ch = readChar();
      return *this;
   }

   /**
    * Receives an unsigned long
    *
    * @param[out] value Where to place value read
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &operator >>(unsigned long &value) {
      return read(value, fRadix);
   }

   /**
    * Receives a long
    *
    * @param[out] value Where to place value read
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &operator >>(long &value) {
      return read(value, fRadix);
   }

   /**
    * Receives an unsigned long
    *
    * @param[out] value Where to place value read
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &operator >>(unsigned int &value) {
      return read(value, fRadix);
   }

   /**
    * Receives an integer
    *
    * @param[out] value Where to place value read
    *
    * @return Reference to the Uart
    *
    * @note Skips leading whitespace
    */
   Uart INLINE_RELEASE &operator >>(int &value) {
      return read(value, fRadix);
   }

   /**
    * Get conversion radix for given base
    *
    * @param[in]  radix Base to convert to radix [2..16]
    *
    * @return Radix corresponding to base
    */
   static constexpr Radix radix(int radix) {
      return (Radix)radix;
   }

   /**
    * Clear UART error status
    */
   virtual void clearError() = 0;

   /**
    * Enable/disable an interrupt source
    *
    * @param[in] uartInterrupt Interrupt source to modify
    * @param[in] enable        True to enable, false to disable
    *
    * @note Changing the enabled interrupt functions may also affect the DMA settings
    */
   void enableInterrupt(UartInterrupt uartInterrupt, bool enable=true) {
      if (enable) {
#ifdef UART_C5_TDMAS
         uart->C5 &= ~uartInterrupt; // DMA must be off to enable interrupts
#endif
         uart->C2 |= uartInterrupt;
      }
      else {
         uart->C2 &= ~uartInterrupt; // May also disable DMA
      }
   }

   /**
    * Enable/disable a DMA source
    *
    * @param[in] uartDma  Interrupt source to modify
    * @param[in] enable   True to enable, false to disable
    *
    * @note Changing the enabled DMA functions may also affect the interrupt settings
    */
   void enableDma(UartDma uartDma, bool enable=true) {
      // Flags are in same positions in the C3 and C5
      if (enable) {
         uart->C5 |= uartDma;
#ifdef UART_C5_TDMAS
         uart->C2 |= uartDma; // Interrupts must be enable for DMA
#endif
      }
      else {
#ifdef UART_C5_TDMAS
         uart->C2 &= ~uartDma; // Switching DMA off shouldn't enable interrupts!
#endif
         uart->C5 &= ~uartDma;
      }
   }
};

/**
 * @brief Template class representing an UART interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart0 = new USBDM::Uart_T<Uart1Info>(DEFAULT_BAUD_RATE, SYSTEM_UART0_CLOCK);
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
template<class Info> class Uart_T : public Uart {
public:
   /**
    * Construct UART interface
    *
    * @param[in]  baudrate         Interface speed in bits-per-second
    */
   Uart_T(unsigned baudrate) : Uart(Info::uart) {
      // Enable clock to UART interface
      *Info::clockReg |= Info::clockMask;

      // Configure pins
      Info::initPCRs();
      setBaudRate(baudrate);
   }

   ~Uart_T() {}

   /**
    * Set baud factor value for interface
    *
    * This is calculated from baud rate and LPUART clock frequency
    *
    * @param[in]  baudrate Interface speed in bits-per-second
    */
   void INLINE_RELEASE setBaudRate(unsigned baudrate) {
      Uart::setBaudRate(baudrate, Info::getInputClockFrequency());
   }

protected:
   /**
    * Clear UART error status
    */
   virtual void clearError() {
      if (Info::statusNeedsWrite) {
         uart->S1 = 0xFF;
      }
      else {
         (void)uart->D;
      }
   }
};

/**
 * Type definition for UART interrupt call back
 *
 *  @param[in]  status - Interrupt flags e.g. UART_S1_TDRE, UART_S1_RDRF etc
 */
typedef void (*UARTCallbackFunction)(uint8_t status);

/**
 * Template class to provide UART callback
 */
template<class Info>
class UartIrq_T : public Uart_T<Info> {

protected:
   /** Callback function for ISR */
   static UARTCallbackFunction rxTxCallback;
   static UARTCallbackFunction errorCallback;

   static void unexpectedInterrupt(uint8_t) {
      setAndCheckErrorCode(E_NO_HANDLER);
   }

   UartIrq_T(unsigned baud) : Uart_T<Info>(baud) {
   }

public:
   /**
    * Receive/Transmit IRQ handler
    */
   static void irqRxTxHandler(void) {
      uint8_t status = Info::uart->S1;
      rxTxCallback(status);
   }

   /**
    * Error and LON event IRQ handler
    */
   static void irqErrorHandler(void) {
      uint8_t status = Info::uart->S1;
      errorCallback(status);
   }

   /**
    * Set Receive/Transmit Callback function
    *
    *   @param[in]  callback Callback function to be executed on UART receive or transmit
    */
   static void setRxTxCallback(UARTCallbackFunction callback) {
      if (callback == nullptr) {
         rxTxCallback = unexpectedInterrupt;
      }
      rxTxCallback = callback;
   }

   /**
    * Set Error Callback function
    *
    *   @param[in]  callback Callback function to be executed on UART receive or transmit
    */
   static void setErrorCallback(UARTCallbackFunction callback) {
      if (callback == nullptr) {
         errorCallback = unexpectedInterrupt;
      }
      errorCallback = callback;
   }
};

template<class Info> UARTCallbackFunction UartIrq_T<Info>::rxTxCallback  = unexpectedInterrupt;
template<class Info> UARTCallbackFunction UartIrq_T<Info>::errorCallback = unexpectedInterrupt;

#ifdef USBDM_UART0_IS_DEFINED
/**
 * @brief Class representing UART0 interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart = new USBDM::Uart1();
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
class Uart0 : public UartIrq_T<Uart0Info> {
public:
   Uart0(unsigned baud=Uart0Info::defaultBaudRate) : UartIrq_T(baud) {
   }
};
#endif

#ifdef USBDM_UART1_IS_DEFINED
/**
 * @brief Class representing UART1 interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart = new USBDM::Uart1();
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
class Uart1 : public UartIrq_T<Uart1Info> {
public:
   /**
    * Construct UART interface
    *
    * @param[in]  baudrate         Interface speed in bits-per-second
    */
   Uart1(unsigned baudrate=Uart1Info::defaultBaudRate) : UartIrq_T(baudrate) {
   }
};
#endif

#ifdef USBDM_UART2_IS_DEFINED
/**
 * @brief Class representing UART2 interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart = new USBDM::Uart2();
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
class Uart2 : public UartIrq_T<Uart2Info> {
public:
   /**
    * Construct UART interface
    *
    * @param[in]  baudrate         Interface speed in bits-per-second
    */
   Uart2(unsigned baudrate=Uart2Info::defaultBaudRate) : UartIrq_T(baudrate) {
   }
};
#endif

#ifdef USBDM_UART3_IS_DEFINED
/**
 * @brief Class representing UART3 interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart = new USBDM::Uart3();
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
class Uart3 : public UartIrq_T<Uart3Info> {
public:
   /**
    * Construct UART interface
    *
    * @param[in]  baudrate         Interface speed in bits-per-second
    * @param[in]  clockFrequency   Frequency of UART clock (SystemCoreClock or SystemBusClock)
    */
   Uart3(unsigned baudrate=Uart3Info::defaultBaudRate) : UartIrq_T(baudrate) {
   }
};
#endif

#ifdef USBDM_UART4_IS_DEFINED
/**
 * @brief Class representing UART4 interface
 *
 * <b>Example</b>
 * @code
 *  // Instantiate interface
 *  Uart *uart = new USBDM::Uart4();
 *
 *  // Transmit data
 *  const uint8_t txDataBuffer[] = {0x11, 0x22, 0x33, 0x44};
 *
 *  // Receive buffer
 *  uint8_t rxDataBuffer[5];
 *
 *  for(;;) {
 *     // Transmit block
 *     uart->transmit(txDataBuffer, sizeof(txDataBuffer));
 *
 *     // Receive block
 *     uart->receive((rxDataBuffer, sizeof(rxDataBuffer));
 *  }
 *  @endcode
 *
 * @tparam Info   Class describing UART hardware
 */
class Uart4 : public UartIrq_T<Uart4Info> {
public:
   /**
    * Construct UART interface
    *
    * @param[in]  baudrate         Interface speed in bits-per-second
    * @param[in]  clockFrequency   Frequency of UART clock (SystemCoreClock or SystemBusClock)
    */
   Uart4(unsigned baudrate=Uart4Info::defaultBaudRate) : UartIrq_T(baudrate) {
   }
};
#endif

/**
 * @}
 */

} // End namespace USBDM

#endif /* INCLUDE_USBDM_UART_H_ */
