 /**
  * @file     gpio.cpp (from gpio-MK20D5.cpp)
  *
  * @brief   Pin declarations for MK20D5
  */

#include "utilities.h"
#include "gpio.h"
#include "pin_mapping.h"

/**
 * @brief Create Timer Clock register name from timer number
 *
 * @param number Timer number e.g. 1 => FTM1_CLOCK_REG
 */
#define FTM_CLOCK_REG(number)  CONCAT3_(FTM,number,_CLOCK_REG)

/**
 * @brief Create Timer Clock register mask from timer number
 *
 * @param number Timer number e.g. 1 => FTM1_CLOCK_MASK
 */
#define FTM_CLOCK_MASK(number)  CONCAT3_(FTM,number,_CLOCK_MASK)

/**
 * @brief Create ADC Clock register name from ADC number
 *
 * @param number Timer number e.g. 1 => ADC1_CLOCK_REG
 */
#define ADC_CLOCK_REG(number)  CONCAT3_(ADC,number,_CLOCK_REG)

/**
 * @brief Create ADC Clock register mask from ADC number
 *
 * @param number Timer number e.g. 1 => ADC1_CLOCK_MASK
 */
#define ADC_CLOCK_MASK(number)  CONCAT3_(ADC,number,_CLOCK_MASK)

#define ADC(num)             CONCAT2_(ADC,num)   
#define FTM(num)             CONCAT2_(FTM,num)   
#define TPM(num)             CONCAT2_(TPM,num)   

const DigitalIO digitalIO_PTA0     = {&PCR(PTA0_GPIO_NAME,PTA0_GPIO_BIT),GPIO(PTA0_GPIO_NAME),PORT_CLOCK_MASK(PTA0_GPIO_NAME),(1UL<<PTA0_GPIO_BIT)};
const DigitalIO digitalIO_PTA1     = {&PCR(PTA1_GPIO_NAME,PTA1_GPIO_BIT),GPIO(PTA1_GPIO_NAME),PORT_CLOCK_MASK(PTA1_GPIO_NAME),(1UL<<PTA1_GPIO_BIT)};
const DigitalIO digitalIO_PTA2     = {&PCR(PTA2_GPIO_NAME,PTA2_GPIO_BIT),GPIO(PTA2_GPIO_NAME),PORT_CLOCK_MASK(PTA2_GPIO_NAME),(1UL<<PTA2_GPIO_BIT)};
const DigitalIO digitalIO_PTA3     = {&PCR(PTA3_GPIO_NAME,PTA3_GPIO_BIT),GPIO(PTA3_GPIO_NAME),PORT_CLOCK_MASK(PTA3_GPIO_NAME),(1UL<<PTA3_GPIO_BIT)};
const DigitalIO digitalIO_PTA4     = {&PCR(PTA4_GPIO_NAME,PTA4_GPIO_BIT),GPIO(PTA4_GPIO_NAME),PORT_CLOCK_MASK(PTA4_GPIO_NAME),(1UL<<PTA4_GPIO_BIT)};
const DigitalIO digitalIO_PTA5     = {&PCR(PTA5_GPIO_NAME,PTA5_GPIO_BIT),GPIO(PTA5_GPIO_NAME),PORT_CLOCK_MASK(PTA5_GPIO_NAME),(1UL<<PTA5_GPIO_BIT)};
const DigitalIO digitalIO_PTA12    = {&PCR(PTA12_GPIO_NAME,PTA12_GPIO_BIT),GPIO(PTA12_GPIO_NAME),PORT_CLOCK_MASK(PTA12_GPIO_NAME),(1UL<<PTA12_GPIO_BIT)};
const DigitalIO digitalIO_PTA13    = {&PCR(PTA13_GPIO_NAME,PTA13_GPIO_BIT),GPIO(PTA13_GPIO_NAME),PORT_CLOCK_MASK(PTA13_GPIO_NAME),(1UL<<PTA13_GPIO_BIT)};
const DigitalIO digitalIO_PTA18    = {&PCR(PTA18_GPIO_NAME,PTA18_GPIO_BIT),GPIO(PTA18_GPIO_NAME),PORT_CLOCK_MASK(PTA18_GPIO_NAME),(1UL<<PTA18_GPIO_BIT)};
const DigitalIO digitalIO_PTA19    = {&PCR(PTA19_GPIO_NAME,PTA19_GPIO_BIT),GPIO(PTA19_GPIO_NAME),PORT_CLOCK_MASK(PTA19_GPIO_NAME),(1UL<<PTA19_GPIO_BIT)};
const DigitalIO digitalIO_PTB0     = {&PCR(PTB0_GPIO_NAME,PTB0_GPIO_BIT),GPIO(PTB0_GPIO_NAME),PORT_CLOCK_MASK(PTB0_GPIO_NAME),(1UL<<PTB0_GPIO_BIT)};
const DigitalIO digitalIO_PTB1     = {&PCR(PTB1_GPIO_NAME,PTB1_GPIO_BIT),GPIO(PTB1_GPIO_NAME),PORT_CLOCK_MASK(PTB1_GPIO_NAME),(1UL<<PTB1_GPIO_BIT)};
const DigitalIO digitalIO_PTB2     = {&PCR(PTB2_GPIO_NAME,PTB2_GPIO_BIT),GPIO(PTB2_GPIO_NAME),PORT_CLOCK_MASK(PTB2_GPIO_NAME),(1UL<<PTB2_GPIO_BIT)};
const DigitalIO digitalIO_PTB3     = {&PCR(PTB3_GPIO_NAME,PTB3_GPIO_BIT),GPIO(PTB3_GPIO_NAME),PORT_CLOCK_MASK(PTB3_GPIO_NAME),(1UL<<PTB3_GPIO_BIT)};
const DigitalIO digitalIO_PTB16    = {&PCR(PTB16_GPIO_NAME,PTB16_GPIO_BIT),GPIO(PTB16_GPIO_NAME),PORT_CLOCK_MASK(PTB16_GPIO_NAME),(1UL<<PTB16_GPIO_BIT)};
const DigitalIO digitalIO_PTB17    = {&PCR(PTB17_GPIO_NAME,PTB17_GPIO_BIT),GPIO(PTB17_GPIO_NAME),PORT_CLOCK_MASK(PTB17_GPIO_NAME),(1UL<<PTB17_GPIO_BIT)};
const DigitalIO digitalIO_PTB18    = {&PCR(PTB18_GPIO_NAME,PTB18_GPIO_BIT),GPIO(PTB18_GPIO_NAME),PORT_CLOCK_MASK(PTB18_GPIO_NAME),(1UL<<PTB18_GPIO_BIT)};
const DigitalIO digitalIO_PTB19    = {&PCR(PTB19_GPIO_NAME,PTB19_GPIO_BIT),GPIO(PTB19_GPIO_NAME),PORT_CLOCK_MASK(PTB19_GPIO_NAME),(1UL<<PTB19_GPIO_BIT)};
const DigitalIO digitalIO_PTC0     = {&PCR(PTC0_GPIO_NAME,PTC0_GPIO_BIT),GPIO(PTC0_GPIO_NAME),PORT_CLOCK_MASK(PTC0_GPIO_NAME),(1UL<<PTC0_GPIO_BIT)};
const DigitalIO digitalIO_PTC1     = {&PCR(PTC1_GPIO_NAME,PTC1_GPIO_BIT),GPIO(PTC1_GPIO_NAME),PORT_CLOCK_MASK(PTC1_GPIO_NAME),(1UL<<PTC1_GPIO_BIT)};
const DigitalIO digitalIO_PTC2     = {&PCR(PTC2_GPIO_NAME,PTC2_GPIO_BIT),GPIO(PTC2_GPIO_NAME),PORT_CLOCK_MASK(PTC2_GPIO_NAME),(1UL<<PTC2_GPIO_BIT)};
const DigitalIO digitalIO_PTC3     = {&PCR(PTC3_GPIO_NAME,PTC3_GPIO_BIT),GPIO(PTC3_GPIO_NAME),PORT_CLOCK_MASK(PTC3_GPIO_NAME),(1UL<<PTC3_GPIO_BIT)};
const DigitalIO digitalIO_PTC4     = {&PCR(PTC4_GPIO_NAME,PTC4_GPIO_BIT),GPIO(PTC4_GPIO_NAME),PORT_CLOCK_MASK(PTC4_GPIO_NAME),(1UL<<PTC4_GPIO_BIT)};
const DigitalIO digitalIO_PTC5     = {&PCR(PTC5_GPIO_NAME,PTC5_GPIO_BIT),GPIO(PTC5_GPIO_NAME),PORT_CLOCK_MASK(PTC5_GPIO_NAME),(1UL<<PTC5_GPIO_BIT)};
const DigitalIO digitalIO_PTC6     = {&PCR(PTC6_GPIO_NAME,PTC6_GPIO_BIT),GPIO(PTC6_GPIO_NAME),PORT_CLOCK_MASK(PTC6_GPIO_NAME),(1UL<<PTC6_GPIO_BIT)};
const DigitalIO digitalIO_PTC7     = {&PCR(PTC7_GPIO_NAME,PTC7_GPIO_BIT),GPIO(PTC7_GPIO_NAME),PORT_CLOCK_MASK(PTC7_GPIO_NAME),(1UL<<PTC7_GPIO_BIT)};
const DigitalIO digitalIO_PTC8     = {&PCR(PTC8_GPIO_NAME,PTC8_GPIO_BIT),GPIO(PTC8_GPIO_NAME),PORT_CLOCK_MASK(PTC8_GPIO_NAME),(1UL<<PTC8_GPIO_BIT)};
const DigitalIO digitalIO_PTC9     = {&PCR(PTC9_GPIO_NAME,PTC9_GPIO_BIT),GPIO(PTC9_GPIO_NAME),PORT_CLOCK_MASK(PTC9_GPIO_NAME),(1UL<<PTC9_GPIO_BIT)};
const DigitalIO digitalIO_PTC10    = {&PCR(PTC10_GPIO_NAME,PTC10_GPIO_BIT),GPIO(PTC10_GPIO_NAME),PORT_CLOCK_MASK(PTC10_GPIO_NAME),(1UL<<PTC10_GPIO_BIT)};
const DigitalIO digitalIO_PTC11    = {&PCR(PTC11_GPIO_NAME,PTC11_GPIO_BIT),GPIO(PTC11_GPIO_NAME),PORT_CLOCK_MASK(PTC11_GPIO_NAME),(1UL<<PTC11_GPIO_BIT)};
const DigitalIO digitalIO_PTD0     = {&PCR(PTD0_GPIO_NAME,PTD0_GPIO_BIT),GPIO(PTD0_GPIO_NAME),PORT_CLOCK_MASK(PTD0_GPIO_NAME),(1UL<<PTD0_GPIO_BIT)};
const DigitalIO digitalIO_PTD1     = {&PCR(PTD1_GPIO_NAME,PTD1_GPIO_BIT),GPIO(PTD1_GPIO_NAME),PORT_CLOCK_MASK(PTD1_GPIO_NAME),(1UL<<PTD1_GPIO_BIT)};
const DigitalIO digitalIO_PTD2     = {&PCR(PTD2_GPIO_NAME,PTD2_GPIO_BIT),GPIO(PTD2_GPIO_NAME),PORT_CLOCK_MASK(PTD2_GPIO_NAME),(1UL<<PTD2_GPIO_BIT)};
const DigitalIO digitalIO_PTD3     = {&PCR(PTD3_GPIO_NAME,PTD3_GPIO_BIT),GPIO(PTD3_GPIO_NAME),PORT_CLOCK_MASK(PTD3_GPIO_NAME),(1UL<<PTD3_GPIO_BIT)};
const DigitalIO digitalIO_PTD4     = {&PCR(PTD4_GPIO_NAME,PTD4_GPIO_BIT),GPIO(PTD4_GPIO_NAME),PORT_CLOCK_MASK(PTD4_GPIO_NAME),(1UL<<PTD4_GPIO_BIT)};
const DigitalIO digitalIO_PTD5     = {&PCR(PTD5_GPIO_NAME,PTD5_GPIO_BIT),GPIO(PTD5_GPIO_NAME),PORT_CLOCK_MASK(PTD5_GPIO_NAME),(1UL<<PTD5_GPIO_BIT)};
const DigitalIO digitalIO_PTD6     = {&PCR(PTD6_GPIO_NAME,PTD6_GPIO_BIT),GPIO(PTD6_GPIO_NAME),PORT_CLOCK_MASK(PTD6_GPIO_NAME),(1UL<<PTD6_GPIO_BIT)};
const DigitalIO digitalIO_PTD7     = {&PCR(PTD7_GPIO_NAME,PTD7_GPIO_BIT),GPIO(PTD7_GPIO_NAME),PORT_CLOCK_MASK(PTD7_GPIO_NAME),(1UL<<PTD7_GPIO_BIT)};
const DigitalIO digitalIO_PTE0     = {&PCR(PTE0_GPIO_NAME,PTE0_GPIO_BIT),GPIO(PTE0_GPIO_NAME),PORT_CLOCK_MASK(PTE0_GPIO_NAME),(1UL<<PTE0_GPIO_BIT)};
const DigitalIO digitalIO_PTE1     = {&PCR(PTE1_GPIO_NAME,PTE1_GPIO_BIT),GPIO(PTE1_GPIO_NAME),PORT_CLOCK_MASK(PTE1_GPIO_NAME),(1UL<<PTE1_GPIO_BIT)};
const AnalogueIO analogueIO_ADC0_SE23   = {0,                ADC(ADC0_SE23_ADC_NUM),&ADC_CLOCK_REG(ADC0_SE23_ADC_NUM),ADC_CLOCK_MASK(ADC0_SE23_ADC_NUM),ADC0_SE23_ADC_CH};
const AnalogueIO analogueIO_PTB0        = {&digitalIO_PTB0,  ADC(PTB0_ADC_NUM),  &ADC_CLOCK_REG(PTB0_ADC_NUM),  ADC_CLOCK_MASK(PTB0_ADC_NUM),  PTB0_ADC_CH};
const AnalogueIO analogueIO_PTB1        = {&digitalIO_PTB1,  ADC(PTB1_ADC_NUM),  &ADC_CLOCK_REG(PTB1_ADC_NUM),  ADC_CLOCK_MASK(PTB1_ADC_NUM),  PTB1_ADC_CH};
const AnalogueIO analogueIO_PTB2        = {&digitalIO_PTB2,  ADC(PTB2_ADC_NUM),  &ADC_CLOCK_REG(PTB2_ADC_NUM),  ADC_CLOCK_MASK(PTB2_ADC_NUM),  PTB2_ADC_CH};
const AnalogueIO analogueIO_PTB3        = {&digitalIO_PTB3,  ADC(PTB3_ADC_NUM),  &ADC_CLOCK_REG(PTB3_ADC_NUM),  ADC_CLOCK_MASK(PTB3_ADC_NUM),  PTB3_ADC_CH};
const AnalogueIO analogueIO_PTC0        = {&digitalIO_PTC0,  ADC(PTC0_ADC_NUM),  &ADC_CLOCK_REG(PTC0_ADC_NUM),  ADC_CLOCK_MASK(PTC0_ADC_NUM),  PTC0_ADC_CH};
const AnalogueIO analogueIO_PTC1        = {&digitalIO_PTC1,  ADC(PTC1_ADC_NUM),  &ADC_CLOCK_REG(PTC1_ADC_NUM),  ADC_CLOCK_MASK(PTC1_ADC_NUM),  PTC1_ADC_CH};
const AnalogueIO analogueIO_PTC2        = {&digitalIO_PTC2,  ADC(PTC2_ADC_NUM),  &ADC_CLOCK_REG(PTC2_ADC_NUM),  ADC_CLOCK_MASK(PTC2_ADC_NUM),  PTC2_ADC_CH};
const AnalogueIO analogueIO_PTD1        = {&digitalIO_PTD1,  ADC(PTD1_ADC_NUM),  &ADC_CLOCK_REG(PTD1_ADC_NUM),  ADC_CLOCK_MASK(PTD1_ADC_NUM),  PTD1_ADC_CH};
const AnalogueIO analogueIO_PTD5        = {&digitalIO_PTD5,  ADC(PTD5_ADC_NUM),  &ADC_CLOCK_REG(PTD5_ADC_NUM),  ADC_CLOCK_MASK(PTD5_ADC_NUM),  PTD5_ADC_CH};
const AnalogueIO analogueIO_PTD6        = {&digitalIO_PTD6,  ADC(PTD6_ADC_NUM),  &ADC_CLOCK_REG(PTD6_ADC_NUM),  ADC_CLOCK_MASK(PTD6_ADC_NUM),  PTD6_ADC_CH};
#if FTM0_5_SEL == 1
const PwmIO  pwmIO_PTA0      = {&digitalIO_PTA0,   (volatile FTM_Type*)FTM(PTA0_FTM_NUM),  PTA0_FTM_CH,   PORT_PCR_MUX(PTA0_FTM_FN),  &FTM_CLOCK_REG(PTA0_FTM_NUM),  FTM_CLOCK_MASK(PTA0_FTM_NUM)};
#endif
#if FTM0_6_SEL == 1
const PwmIO  pwmIO_PTA1      = {&digitalIO_PTA1,   (volatile FTM_Type*)FTM(PTA1_FTM_NUM),  PTA1_FTM_CH,   PORT_PCR_MUX(PTA1_FTM_FN),  &FTM_CLOCK_REG(PTA1_FTM_NUM),  FTM_CLOCK_MASK(PTA1_FTM_NUM)};
#endif
#if FTM0_7_SEL == 1
const PwmIO  pwmIO_PTA2      = {&digitalIO_PTA2,   (volatile FTM_Type*)FTM(PTA2_FTM_NUM),  PTA2_FTM_CH,   PORT_PCR_MUX(PTA2_FTM_FN),  &FTM_CLOCK_REG(PTA2_FTM_NUM),  FTM_CLOCK_MASK(PTA2_FTM_NUM)};
#endif
#if FTM0_0_SEL == 1
const PwmIO  pwmIO_PTA3      = {&digitalIO_PTA3,   (volatile FTM_Type*)FTM(PTA3_FTM_NUM),  PTA3_FTM_CH,   PORT_PCR_MUX(PTA3_FTM_FN),  &FTM_CLOCK_REG(PTA3_FTM_NUM),  FTM_CLOCK_MASK(PTA3_FTM_NUM)};
#endif
#if FTM0_1_SEL == 1
const PwmIO  pwmIO_PTA4      = {&digitalIO_PTA4,   (volatile FTM_Type*)FTM(PTA4_FTM_NUM),  PTA4_FTM_CH,   PORT_PCR_MUX(PTA4_FTM_FN),  &FTM_CLOCK_REG(PTA4_FTM_NUM),  FTM_CLOCK_MASK(PTA4_FTM_NUM)};
#endif
#if FTM0_2_SEL == 1
const PwmIO  pwmIO_PTA5      = {&digitalIO_PTA5,   (volatile FTM_Type*)FTM(PTA5_FTM_NUM),  PTA5_FTM_CH,   PORT_PCR_MUX(PTA5_FTM_FN),  &FTM_CLOCK_REG(PTA5_FTM_NUM),  FTM_CLOCK_MASK(PTA5_FTM_NUM)};
#endif
#if FTM1_0_SEL == 1
const PwmIO  pwmIO_PTA12     = {&digitalIO_PTA12,  (volatile FTM_Type*)FTM(PTA12_FTM_NUM), PTA12_FTM_CH,  PORT_PCR_MUX(PTA12_FTM_FN), &FTM_CLOCK_REG(PTA12_FTM_NUM), FTM_CLOCK_MASK(PTA12_FTM_NUM)};
#endif
#if FTM1_1_SEL == 1
const PwmIO  pwmIO_PTA13     = {&digitalIO_PTA13,  (volatile FTM_Type*)FTM(PTA13_FTM_NUM), PTA13_FTM_CH,  PORT_PCR_MUX(PTA13_FTM_FN), &FTM_CLOCK_REG(PTA13_FTM_NUM), FTM_CLOCK_MASK(PTA13_FTM_NUM)};
#endif
#if FTM1_0_SEL == 2
const PwmIO  pwmIO_PTB0      = {&digitalIO_PTB0,   (volatile FTM_Type*)FTM(PTB0_FTM_NUM),  PTB0_FTM_CH,   PORT_PCR_MUX(PTB0_FTM_FN),  &FTM_CLOCK_REG(PTB0_FTM_NUM),  FTM_CLOCK_MASK(PTB0_FTM_NUM)};
#endif
#if FTM1_1_SEL == 2
const PwmIO  pwmIO_PTB1      = {&digitalIO_PTB1,   (volatile FTM_Type*)FTM(PTB1_FTM_NUM),  PTB1_FTM_CH,   PORT_PCR_MUX(PTB1_FTM_FN),  &FTM_CLOCK_REG(PTB1_FTM_NUM),  FTM_CLOCK_MASK(PTB1_FTM_NUM)};
#endif
#if FTM0_0_SEL == 2
const PwmIO  pwmIO_PTC1      = {&digitalIO_PTC1,   (volatile FTM_Type*)FTM(PTC1_FTM_NUM),  PTC1_FTM_CH,   PORT_PCR_MUX(PTC1_FTM_FN),  &FTM_CLOCK_REG(PTC1_FTM_NUM),  FTM_CLOCK_MASK(PTC1_FTM_NUM)};
#endif
#if FTM0_1_SEL == 2
const PwmIO  pwmIO_PTC2      = {&digitalIO_PTC2,   (volatile FTM_Type*)FTM(PTC2_FTM_NUM),  PTC2_FTM_CH,   PORT_PCR_MUX(PTC2_FTM_FN),  &FTM_CLOCK_REG(PTC2_FTM_NUM),  FTM_CLOCK_MASK(PTC2_FTM_NUM)};
#endif
#if FTM0_2_SEL == 2
const PwmIO  pwmIO_PTC3      = {&digitalIO_PTC3,   (volatile FTM_Type*)FTM(PTC3_FTM_NUM),  PTC3_FTM_CH,   PORT_PCR_MUX(PTC3_FTM_FN),  &FTM_CLOCK_REG(PTC3_FTM_NUM),  FTM_CLOCK_MASK(PTC3_FTM_NUM)};
#endif
const PwmIO  pwmIO_PTC4      = {&digitalIO_PTC4,   (volatile FTM_Type*)FTM(PTC4_FTM_NUM),  PTC4_FTM_CH,   PORT_PCR_MUX(PTC4_FTM_FN),  &FTM_CLOCK_REG(PTC4_FTM_NUM),  FTM_CLOCK_MASK(PTC4_FTM_NUM)};
const PwmIO  pwmIO_PTD4      = {&digitalIO_PTD4,   (volatile FTM_Type*)FTM(PTD4_FTM_NUM),  PTD4_FTM_CH,   PORT_PCR_MUX(PTD4_FTM_FN),  &FTM_CLOCK_REG(PTD4_FTM_NUM),  FTM_CLOCK_MASK(PTD4_FTM_NUM)};
#if FTM0_5_SEL == 2
const PwmIO  pwmIO_PTD5      = {&digitalIO_PTD5,   (volatile FTM_Type*)FTM(PTD5_FTM_NUM),  PTD5_FTM_CH,   PORT_PCR_MUX(PTD5_FTM_FN),  &FTM_CLOCK_REG(PTD5_FTM_NUM),  FTM_CLOCK_MASK(PTD5_FTM_NUM)};
#endif
#if FTM0_6_SEL == 2
const PwmIO  pwmIO_PTD6      = {&digitalIO_PTD6,   (volatile FTM_Type*)FTM(PTD6_FTM_NUM),  PTD6_FTM_CH,   PORT_PCR_MUX(PTD6_FTM_FN),  &FTM_CLOCK_REG(PTD6_FTM_NUM),  FTM_CLOCK_MASK(PTD6_FTM_NUM)};
#endif
#if FTM0_7_SEL == 2
const PwmIO  pwmIO_PTD7      = {&digitalIO_PTD7,   (volatile FTM_Type*)FTM(PTD7_FTM_NUM),  PTD7_FTM_CH,   PORT_PCR_MUX(PTD7_FTM_FN),  &FTM_CLOCK_REG(PTD7_FTM_NUM),  FTM_CLOCK_MASK(PTD7_FTM_NUM)};
#endif
