#!/bin/bash
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
  rm -fv /usr/doc/parted
fi
# End automatically added section

#======================================================
#  USB Hardware Removal
#======================================================
uninstallUSBHardware() {

   echo
   echo "Removing rules file from ${RULES_DIR}"
   echo "=================================================================="
   rm -fv ${RULES_DIR}/*usbdm.rules
}

#======================================================
#  Eclipse Plugin Removal
#======================================================
# $1 - Eclipse directory
#
uninstallEclipsePlugins() {

   local ECLIPSE_DIR="$1"
   local ECLIPSE_DROPIN_DIR="${ECLIPSE_DIR}/dropins"

   if [[ ! -d ${ECLIPSE_DROPIN_DIR} ]]; then
      echo " Dropin directory ${ECLIPSE_DROPIN_DIR} Not Found"
      return
   fi

   echo 
   echo "Removing Eclipse CDT plugins from ${ECLIPSE_DROPIN_DIR}"
   echo "=================================================================="
   if [[ -d "${ECLIPSE_DROPIN_DIR}/usbdm" ]]; then
      rm -rfv "${ECLIPSE_DROPIN_DIR}/usbdm"
   fi

   echo "Refreshing Eclipse"
   for FILENAME in cwide eclipse; do
      if [[ -x "${ECLIPSE_DIR}/${FILENAME}" ]]; then
         echo "${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash"
         ${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash
      fi
   done
}

#======================================================
#  Eclipse Removal
#======================================================
uninstallEclipse() {

   local ECLIPSE_DIR_LIST="/usr/local/eclipse* /opt/eclipse* /usr/lib/eclipse*"

   echo 
   echo "Checking for Eclipse directories"
   echo "=================================================================="
   for ECLIPSE_DIR in $ECLIPSE_DIR_LIST; do
      echo -n "Looking for Eclipse in '${ECLIPSE_DIR}'"
      if [[ -d ${ECLIPSE_DIR} ]]; then
         echo " - Found"
         uninstallEclipsePlugins ${ECLIPSE_DIR}
      else
        echo " - Not Found"
      fi
   done
}

#======================================================
#  KDS Instance Removal
#======================================================
uninstallKDSInstance() {

   local KDS_DIR="$1"
   local KDS_TOOLCHAIN_LIB_DIR="${KDS_DIR}/toolchain/arm-none-eabi/lib"
   local KDS_ECLIPSE_DIR="${KDS_DIR}/eclipse"
   local KDS_PE_DIR="${KDS_ECLIPSE_DIR}/ProcessorExpert/Config/Compiler"
   local KDS_PR_XLKR_FILENAME="net.sourceforge.usbdm.cdt.arm.toolchain.c.compiler.xlkr"
   local KDS_NANO_SPECS_FILENAME="nano.specs"
   
   # Remove USBDM plugins to eclipse
   uninstallEclipsePlugins ${KDS_ECLIPSE_DIR}

   # Add Toolchain nano.specs files
   local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
   
   echo Removing nano.specs files...
   if [[ -f ${DESTINATION} ]]; then
      rm -fv ${DESTINATION}
   else
     echo " Specs file '${DESTINATION}' - Not Found"
   fi

   # Remove PE files
   local DESTINATION="${KDS_PE_DIR}/${KDS_PR_XLKR_FILENAME}"
   
   echo Removing PE files...
   if [[ -f ${DESTINATION} ]]; then
      rm -fv ${DESTINATION}
   else
     echo " Processor Expert file '${DESTINATION}' - Not Found"
   fi
}

#======================================================
#  KDS Removal
#======================================================
uninstallKDS() {

   local KDS_DIR_LIST="/usr/local/Freescale/KDS_* /opt/Freescale/KDS_*"

   echo 
   echo "Checking for KDS directories"
   echo "=================================================================="
   for KDS_DIR in $KDS_DIR_LIST; do
      echo -n "Looking for Freescale KDS in '${KDS_DIR}'"
      if [[ -d ${KDS_DIR} ]]; then
         echo " - Found"
         uninstallKDSInstance ${KDS_DIR}
      else
         echo " - Not Found"
      fi
   done
}

#======================================================
#  Codewarrior Instance Removal
#======================================================
uninstallCodewarriorInstance() {

   local CODEWARRIOR_DIR="$1"
   local CODEWARRIOR_ECLIPSE_DIR="$1/eclipse"

   if [[ ! -d ${CODEWARRIOR_ECLIPSE_DIR} ]]; then
      echo 
      echo "Codewarrior Eclipse directory '${CODEWARRIOR_ECLIPSE_DIR}'not found"
      echo "=================================================================="
      return
   fi

   CF_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ColdFire/gdi"
   HCS_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/HC08/gdi"
   S12Z_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/S12Z/gdi"
   ARM_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ARM/gdi"
   DSC_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/DSC/gdi"
   CW_PLUGIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/plugins"
   CW_DROPIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/dropins"
   WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
   ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"

   CF_GDI_TARGETS="usbdm-cfv1-gdi.so usbdm-cfvx-gdi.so usbdm-cfv1-gdi-debug.so usbdm-cfvx-gdi-debug.so"
   HCS_GDI_TARGETS="usbdm-hcs08-gdi.so usbdm-rs08-gdi.so usbdm-hcs08-gdi-debug.so usbdm-rs08-gdi-debug.so"
   S12Z_GDI_TARGETS="usbdm-s12z-gdi.so usbdm-s12z-gdi-debug.so"
   ARM_GDI_TARGETS="usbdm-arm-gdi.so usbdm-arm-gdi-debug.so"
   DSC_GDI_TARGETS="usbdm-dsc-gdi.so usbdm-dsc-gdi-debug.so"

   echo
   echo "Removing CFV1 & CFVx GDI files from '${CF_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${CF_GDI_TARGETS}; do
      local DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing RS08 & HCS08 GDI files from '${HCS_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${HCS_GDI_TARGETS}; do
      local DESTINATION="${HCS_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing S12Z GDI files from '${S12Z_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${S12Z_GDI_TARGETS}; do
      local DESTINATION="${S12Z_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Kinetis GDI files from '${ARM_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${ARM_GDI_TARGETS}; do
      local DESTINATION="${ARM_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing DSC GDI files from '${DSC_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${DSC_GDI_TARGETS}; do
      local DESTINATION="${DSC_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Codewarrior Project Wizard Files for USBDM"
   echo "=================================================================="
   echo "Removing launch settings"
   rm -vf ${WIZARD_DIRECTORY}/launch_config/usbdm*

   echo
   echo "Unpatching New Project Wizard"
   CODEWARRIOR_PATCH_NEW_WIZARD="PatchNewWizardPlugin_V10.2.xml"
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.projectwizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   echo
   echo "Unpatching Change Project Wizard"
   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_CHANGE_WIZARD}
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml

   echo 
   echo "Refreshing Eclipse"
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   uninstallEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}"
}

#======================================================
#  Codewarrior Removal
#======================================================
uninstallCodewarrior() {

   echo 
   echo "Checking for Codewarrior directory"
   echo "=================================================================="
   for CODEWARRIOR_DIR in "/usr/local/Freescale/CodeWarrior_MCU_10.2" "/opt/Freescale/CodeWarrior_MCU_10.2" ; do
      echo -n "Looking for Codewarrior in '${CODEWARRIOR_DIR}'"
      if [[ -d ${CODEWARRIOR_DIR} ]]; then
         echo " - Found"
         uninstallCodewarriorInstance ${CODEWARRIOR_DIR}
      else
         echo " - Not Found"
      fi
   done

}

#================================
# USBDM Version
#
MAJOR=4
MINOR=10
VERSION=${MAJOR}.${MINOR}

# Where to find files (relative to /)
DUMMY_ROOT=""
USBDM_BIN_DIR="${DUMMY_ROOT}/usr/bin"
USBDM_LIB_DIR64="${DUMMY_ROOT}/usr/lib/x86_64-linux-gnu/usbdm"
USBDM_LIB_DIR32="${DUMMY_ROOT}/usr/lib/i386-linux-gnu/usbdm"

BITNESS=`getconf LONG_BIT`
if [[ ${BITNESS} == 32 ]]; then
   USBDM_LIB_DIR=${USBDM_LIB_DIR32}
else
   USBDM_LIB_DIR=${USBDM_LIB_DIR64}
fi 

USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
USBDM_CDT_PLUGINS_DIR="${USBDM_SHARED_DIR}/CDT_Plugins"
USBDM_CW_PLUGINS_DIR="${USBDM_SHARED_DIR}/CW_Plugins"
USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"

# System directories
LIB_DIR="/usr/lib"
BIN_DIR="/usr/bin"
RULES_DIR="/etc/udev/rules.d"

uninstallUSBHardware
uninstallEclipse
uninstallKDS
uninstallCodewarrior

