#!/bin/bash
set -e

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
  rm -fv /usr/doc/parted
fi
# End automatically added section

#======================================================
#  USB Hardware Removal
#======================================================
removeUSBHardware() {

   echo
   echo "Removing rules file from ${RULES_DIR}"
   echo "=================================================================="
   rm -fv ${RULES_DIR}/*usbdm.rules
}

#======================================================
#  Eclipse Plugin Removal
#======================================================
# $1 - Eclipse directory
# $2 - Feature Group
#
removeEclipsePlugins() {

   P2_APPLICATION="org.eclipse.equinox.p2.director"

   local ECLIPSE_DIR="$1"
   local FEATURE_GROUP="$2"

   echo 
   echo "Removing USBDM Eclipse CDT plugins from ${ECLIPSE_DIR}"
   echo "=================================================================="
   for FILENAME in kinetis-design-studio cwide eclipse; do
      if [[ -x "${ECLIPSE_DIR}/${FILENAME}" ]]; then
         echo ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP}
         ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP} || true
         break
      fi
   done
}

#======================================================
#  Eclipse Removal
#======================================================
removeEclipse() {

   local ECLIPSE_DIR_LIST="/usr/local/eclipse* /opt/eclipse* /usr/lib/eclipse*"

   echo 
   echo "Checking for Eclipse directories"
   echo "=================================================================="
   for ECLIPSE_DIR in $ECLIPSE_DIR_LIST; do
      echo -n "Looking for Eclipse in '${ECLIPSE_DIR}'"
      if [[ -d ${ECLIPSE_DIR} ]]; then
         echo " - Found"
         removeEclipsePlugins ${ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
      else
        echo " - Not Found"
      fi
   done
}

#======================================================
#  KDS Instance Removal
#======================================================
removeKDSInstance() {

   local KDS_DIR="$1"
   local KDS_TOOLCHAIN_LIB_DIR="${KDS_DIR}/toolchain/arm-none-eabi/lib"
   local KDS_ECLIPSE_DIR="${KDS_DIR}/eclipse"
   local KDS_ECLIPSE_PLUGIN_DIR="${KDS_DIR}/eclipse/plugins"

   local KDS_PE_COMPILER_DIR="${KDS_ECLIPSE_DIR}/ProcessorExpert/Config/Compiler"
   local KDS_PE_WIZARD_DIR="${KDS_ECLIPSE_DIR}/ProcessorExpert/Config/PE/CPE/wizard_data/wizards"
   local KDS_PE_WIZARD_LAUNCH_DIR="${KDS_PE_WIZARD_DIR}/launch_config"

   local KDS_VER="3_0_0"

   echo
   echo "UnPatching KDS New Project Wizard"
   local WIZARD_PATCH_FILE=${USBDM_WIZARD_PATCH_DIR}/"PatchNewWizardPlugin_KDS_${KDS_VER}.xml"
   local WIZARD_BASE_DIR=${KDS_ECLIPSE_PLUGIN_DIR}/"com.freescale.processorexpert.ui.kds.newprojectwizard_"
   echo ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   echo
   echo "UnPatching KDS Launch Config Information"
   local LAUNCH_PATCH_FILE=${USBDM_WIZARD_PATCH_DIR}/"PatchLaunchConfiguration_KDS_${KDS_VER}.xml"
   local LAUNCH_BASE_DIR=${KDS_PE_WIZARD_DIR}/kd
   echo ${USBDM_BIN_DIR}/MergeXML ${LAUNCH_BASE_DIR}\* "_sdk.xml"
   ${USBDM_BIN_DIR}/MergeXML ${LAUNCH_BASE_DIR}\* "_sdk.xml"
   echo touch ${LAUNCH_BASE_DIR}\*
   touch ${LAUNCH_BASE_DIR}*

   # Remove PE files
   echo "Removing PE files..."
   echo

   local DESTINATION="${KDS_PE_WIZARD_LAUNCH_DIR}/launch_gdb_usbdm.xml"

   if [[ -d ${DESTINATION} ]]; then
      echo "Removing KDS USBDM Launch config"
      rm -fv ${DESTINATION}
   else
      echo " KDS Launch config file '${DESTINATION}' - Not Found"
   fi

   local KDS_PR_XLKR_FILENAME="net.sourceforge.usbdm.cdt.arm.toolchain.c.compiler.xlkr"

   local DESTINATION="${KDS_PE_COMPILER_DIR}/${KDS_PR_XLKR_FILENAME}"
   
   if [[ -f ${DESTINATION} ]]; then
      echo "Removing xlkr file"
      rm -fv ${DESTINATION}
   else
     echo " Processor Expert file '${DESTINATION}' - Not Found"
   fi

   # Remove USBDM plugins to eclipse
   removeEclipsePlugins ${KDS_ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
}

#======================================================
#  KDS Removal
#======================================================
removeKDS() {

   local KDS_DIR_LIST="/usr/local/Freescale/KDS_* /opt/Freescale/KDS_*"

   echo 
   echo "Checking for KDS directories"
   echo "=================================================================="
   for KDS_DIR in $KDS_DIR_LIST; do
      echo -n "Looking for Freescale KDS in '${KDS_DIR}'"
      if [[ -d ${KDS_DIR} ]]; then
         echo " - Found"
         removeKDSInstance ${KDS_DIR}
      else
         echo " - Not Found"
      fi
   done
}

#======================================================
#  Codewarrior Instance Removal
#======================================================
removeCodewarriorInstance() {

   local CODEWARRIOR_DIR="$1"
   local CODEWARRIOR_ECLIPSE_DIR="$1/eclipse"

   if [[ ! -d ${CODEWARRIOR_ECLIPSE_DIR} ]]; then
      echo 
      echo "Codewarrior Eclipse directory '${CODEWARRIOR_ECLIPSE_DIR}'not found"
      echo "=================================================================="
      return
   fi

   CF_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ColdFire/gdi"
   HCS_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/HC08/gdi"
   S12Z_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/S12Z/gdi"
   ARM_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ARM/gdi"
   DSC_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/DSC/gdi"
   CW_PLUGIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/plugins"
   CW_DROPIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/dropins"
   WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
   ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"

   CF_GDI_TARGETS="libusbdm-gdi-cfv1.so libusbdm-gdi-cfvx.so libusbdm-gdi-cfv1-debug.so libusbdm-gdi-cfvx-debug.so"
   HCS_GDI_TARGETS="libusbdm-gdi-hcs08.so libusbdm-gdi-rs08.so libusbdm-gdi-hcs08-debug.so libusbdm-gdi-rs08-debug.so"
   S12Z_GDI_TARGETS="libusbdm-gdi-s12z.so libusbdm-gdi-s12z-debug.so"
   ARM_GDI_TARGETS="libusbdm-gdi-arm.so libusbdm-gdi-arm-debug.so"
   DSC_GDI_TARGETS="libusbdm-gdi-dsc.so libusbdm-gdi-dsc-debug.so"

   echo
   echo "Removing CFV1 & CFVx GDI files from '${CF_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${CF_GDI_TARGETS}; do
      local DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing RS08 & HCS08 GDI files from '${HCS_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${HCS_GDI_TARGETS}; do
      local DESTINATION="${HCS_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing S12Z GDI files from '${S12Z_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${S12Z_GDI_TARGETS}; do
      local DESTINATION="${S12Z_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Kinetis GDI files from '${ARM_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${ARM_GDI_TARGETS}; do
      local DESTINATION="${ARM_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing DSC GDI files from '${DSC_GDI_DIRECTORY}'"
   echo "=================================================================="
   for FILENAME in ${DSC_GDI_TARGETS}; do
      local DESTINATION="${DSC_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Codewarrior Project Wizard Files for USBDM"
   echo "=================================================================="
   echo "Removing launch settings"
   rm -vf ${WIZARD_DIRECTORY}/launch_config/usbdm*

   echo
   echo "Unpatching New Project Wizard"
   CODEWARRIOR_PATCH_NEW_WIZARD="PatchNewWizardPlugin_V10.2.xml"
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.projectwizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   echo
   echo "Unpatching Change Project Wizard"
   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_CHANGE_WIZARD}
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml

   echo 
   echo "Refreshing Eclipse"
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   removeEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${CW_FEATURE_GROUP}
}

#======================================================
#  Codewarrior Removal
#======================================================
removeCodewarrior() {

   echo 
   echo "Checking for Codewarrior directory"
   echo "=================================================================="
   for CODEWARRIOR_DIR in "/usr/local/Freescale/CodeWarrior_MCU_10.2" "/opt/Freescale/CodeWarrior_MCU_10.2" ; do
      echo -n "Looking for Codewarrior in '${CODEWARRIOR_DIR}'"
      if [[ -d ${CODEWARRIOR_DIR} ]]; then
         echo " - Found"
         removeCodewarriorInstance ${CODEWARRIOR_DIR}
      else
         echo " - Not Found"
      fi
   done

}

#================================
# USBDM Version
#
MAJOR=4
MINOR=11
VERSION=${MAJOR}.${MINOR}
CP_OPTIONS=-p

# Where to find files (relative to /)
DUMMY_ROOT=""
USBDM_BIN_DIR="${DUMMY_ROOT}/usr/bin"
USBDM_LIB_DIR64="${DUMMY_ROOT}/usr/lib/x86_64-linux-gnu/usbdm"
USBDM_LIB_DIR32="${DUMMY_ROOT}/usr/lib/i386-linux-gnu/usbdm"

BITNESS=`getconf LONG_BIT`
if [[ ${BITNESS} == 32 ]]; then
   USBDM_LIB_DIR=${USBDM_LIB_DIR32}
else
   USBDM_LIB_DIR=${USBDM_LIB_DIR64}
fi 

USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
USBDM_UPDATE_SITE="${USBDM_SHARED_DIR}/UpdateSite"
USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"

CDT_FEATURE_GROUP="net.sourceforge.usbdm.cdt.feature.feature.group"
CW_FEATURE_GROUP="net.sourceforge.usbdm.cw.feature.feature.group"

# System directories
LIB_DIR="/usr/lib"
BIN_DIR="/usr/bin"
RULES_DIR="/etc/udev/rules.d"

#removeUSBHardware
#removeEclipse
removeKDS
#removeCodewarrior

