#!/bin/bash
set -e

#======================================================
#  Codewarrior Installation
#======================================================
installCodewarrior() {

   echo 
   echo "Checking for Codewarrior directory"
   echo ==================================================================
   for CODEWARRIOR_DIR in "/usr/local/Freescale/CodeWarrior_MCU_10.2" "/opt/Freescale/CodeWarrior_MCU_10.2" ; do
      echo -n "Looking for Codewarrior in ${CODEWARRIOR_DIR}"
      if [[ -d ${CODEWARRIOR_DIR} ]]; then
         echo " - Found"
         break;
      else
         echo " - Not Found"
      fi
   done

   if [[ ! -d ${CODEWARRIOR_DIR} ]]; then
      echo 
      echo "Codewarrior not found"
      echo ======================================================================================
      return
   fi
   CODEWARRIOR_DROPIN_DIR="${CODEWARRIOR_DIR}/eclipse/dropins"

   echo 
   echo "Installing Codewarrior plugins to ${CODEWARRIOR_DROPIN_DIR}"
   echo ======================================================================================
   if [[ -d "${CODEWARRIOR_DROPIN_DIR}/usbdm" ]]; then
      rm -rfv "${CODEWARRIOR_DROPIN_DIR}/usbdm"
   fi
   mkdir -pv "${CODEWARRIOR_DROPIN_DIR}/usbdm"
   ln -svf  ${USBDM_CW_PLUGINS_DIR}/* "${CODEWARRIOR_DROPIN_DIR}/usbdm"

   CF_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ColdFire/gdi"
   HCS_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/HC08/gdi"
   ARM_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ARM/gdi"
   DSC_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/DSC/gdi"
   CW_PLUGIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/plugins"
   CW_DROPIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/dropins"
   WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
   ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"

   CF_GDI_TARGETS="usbdm-cfv1-gdi.so usbdm-cfvx-gdi.so usbdm-cfv1-gdi-debug.so usbdm-cfvx-gdi-debug.so"
   HCS_GDI_TARGETS="usbdm-hcs08-gdi.so usbdm-rs08-gdi.so usbdm-hcs08-gdi-debug.so usbdm-rs08-gdi-debug.so"
   ARM_GDI_TARGETS="usbdm-arm-gdi.so usbdm-arm-gdi-debug.so"
   DSC_GDI_TARGETS="usbdm-dsc-gdi.so usbdm-dsc-gdi-debug.so"

   echo
   echo "Installing CFV1 & CFVx GDI files to ${CF_GDI_DIRECTORY}"
   echo ==================================================================
   echo "Linking ..."
   for FILENAME in ${CF_GDI_TARGETS}; do
      SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
      DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
      ln -svf ${SOURCE} ${DESTINATION}
   done

   echo
   echo "Installing RS08 & HCS08 GDI files"
   echo ==================================================================
   echo "Linking ..."
   for FILENAME in ${HCS_GDI_TARGETS}; do
      SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
      DESTINATION="${HCS_GDI_DIRECTORY}/${FILENAME}"
      ln -svf ${SOURCE} ${DESTINATION}
   done

   echo
   echo "Installing Kinetis GDI files"
   echo ==================================================================
   echo "Linking ..."
   for FILENAME in ${ARM_GDI_TARGETS}; do
      SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
      DESTINATION="${ARM_GDI_DIRECTORY}/${FILENAME}"
      ln -svf ${SOURCE} ${DESTINATION}
   done

   echo
   echo "Installing DSC GDI files"
   echo ==================================================================
   echo "Linking ..."
   for FILENAME in ${DSC_GDI_TARGETS}; do
      SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
      DESTINATION="${DSC_GDI_DIRECTORY}/${FILENAME}"
      ln -svf ${SOURCE} ${DESTINATION}
   done

   echo
   echo "Installing Codewarrior Project Wizard Files for USBDM"
   echo ==================================================================
   echo "Installing launch settings"
   echo "Linking ..."
   ln -svf "${USBDM_CW_LAUNCH_CONFIG_DIR}/"*".xml" ${WIZARD_DIRECTORY}/launch_config

   echo "Patching New Project Wizard"
   CODEWARRIOR_PATCH_NEW_WIZARD="PatchNewWizardPlugin_V10.2.xml"
   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_NEW_WIZARD}
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.projectwizard_"  
   ${USBDM_LIB_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml ${WIZARD_PATCH_FILE}
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   echo "Patching Change Project Wizard"
   CODEWARRIOR_PATCH_CHANGE_WIZARD="PatchChangeWizardPlugin_V10.2.xml"
   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_CHANGE_WIZARD}
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
   ${USBDM_LIB_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml ${WIZARD_PATCH_FILE}

   echo 
   echo "Refreshing Eclipse"
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*
   echo ${ECLIPSE_CWIDE} -clean -initialize
   ${ECLIPSE_CWIDE} -clean -initialize
}

#================================
# USBDM Version
#
MAJOR=4
MINOR=10
VERSION=${MAJOR}.${MINOR}

# Where to find files (relative to /)
DUMMY_ROOT=""
USBDM_LIB_DIR="${DUMMY_ROOT}/usr/lib/usbdm"
USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
USBDM_CDT_PLUGINS_DIR="${USBDM_SHARED_DIR}/CDT_Plugins"
USBDM_CW_PLUGINS_DIR="${USBDM_SHARED_DIR}/CW_Plugins"
USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"

# System directories
LIB_DIR="/usr/lib"
BIN_DIR="/usr/bin"
RULES_DIR="/etc/udev/rules.d"

installCodewarrior

