#!/bin/bash

# Build with native BITNESS
echo make -f Makefile.mk clean
make -f Makefile.mk clean

# Uncomment to build 32-bit binaries on linux 64-bit
#echo make -f Makefile clean BITNESS=32
#make -f Makefile clean BITNESS=32

