#!/bin/sh

# Where files are (relative to script)
HOME_DIR="$(dirname $(readlink -f $0))"

echo "Working in ${HOME_DIR}"

MULTIARCH=`gcc --print-multiarch`
ARCH=`uname -n`

# Where to place test files
TEST_DIR=${HOME_DIR}/Tests

# Where DLLs to link against are kept
DEVICE_DATA=${HOME_DIR}/PackageFiles/DeviceData

mkdir -p ${TEST_DIR}

# Executables that are produced as part of USBDM
cp "${HOME_DIR}/PackageFiles/bin/${MULTIARCH}/"*                "${TEST_DIR}"
cp "${HOME_DIR}/PackageFiles/lib/${MULTIARCH}/"*                "${TEST_DIR}"

# Misc commands
cp "${HOME_DIR}/PackageFiles/Miscellaneous/"*.tcl  "${TEST_DIR}"

# Device Data
cp -P -r "${DEVICE_DATA}"              "${TEST_DIR}/DeviceData"

