#!/bin/bash

MULTIARCH=`gcc --print-multiarch`
ARCH=`uname -m`

clear

SOURCE_DIRECTORY="$(dirname $(readlink -f $0))"
echo "Building DEB file in ${SOURCE_DIRECTORY}"

# Version Information
source ${SOURCE_DIRECTORY}/version

echo "Building Version ${VERSION}"

DATE=`date +"%Y%m%d%H%M%S"`

pausing() {
   x=5
   echo -n Pausing ...
   while [ $x -gt 0 ];  do
      sleep 1s
      echo -n " $x"
      x=$(( $x - 1 ))
   done
   echo 
}

#======================================================
# Create ARCH dependent DEB file
#======================================================
# $1 - BITNESS
#
makeDebFile() {

#   CP="cp -pv"
#   MKDIR="mkdir -pv"
#   RM="rm -f"
#   MV="mv -v"

   CP="cp -p"
   MKDIR="mkdir -p"
   RM="rm -f"
   MV="mv"

   local BITNESS="$1"

   # Where to find libraries and binaries
   USBDM_SOURCE_LIBDIR=${SOURCE_DIRECTORY}/PackageFiles/lib/${MULTIARCH}

   # Where to copy executables from
   USBDM_SOURCE_BINDIR=${SOURCE_DIRECTORY}/PackageFiles/bin/${MULTIARCH}
   
   USBDM_UPDATE_SITE=${SOURCE_DIRECTORY}/../usbdm-eclipse-plugins/UpdateSite

   # Where to construct the install tree
   DUMMY_ROOT="../usbdm_${VERSION}-${DEBIAN_VERSION}-${ARCH}"

   # Where to copy libraries to
   USBDM_LIBDIR="${DUMMY_ROOT}/usr/lib/${MULTIARCH}/usbdm"

   # Shared files
   USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"

   # Shared document files
   USBDM_SHARED_DOC_DIR="${DUMMY_ROOT}/usr/share/doc/usbdm"

   # Binary files
   USBDM_BINDIR="${DUMMY_ROOT}/usr/bin"

   # Control files
   USBDM_CONTROL_DIR="${DUMMY_ROOT}/DEBIAN"

   # Icon files
   PIXMAP_DIR="${DUMMY_ROOT}/usr/share/pixmaps"

   # Where to put .desktop files
   LINUX_APPLICATIONS_DIR="${DUMMY_ROOT}/usr/share/applications"

   # Where to put Man page files
   USBDM_MANUAL_DIR="${DUMMY_ROOT}/usr/share/man/man1"

   # Binary files
   USBDM_RULESDIR="${DUMMY_ROOT}/etc/udev/rules.d"

   if [[ ! -d ${SOURCE_DIRECTORY} ]]; then
      echo Unable to locate Source directory "${SOURCE_DIRECTORY}"
   fi

   if [[ -e ${DUMMY_ROOT} ]]; then
      echo ${RM} -R ${DUMMY_ROOT}
      ${RM} -R ${DUMMY_ROOT}
   fi

   ${MKDIR} ${PIXMAP_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/Hardware-Chip.png ${PIXMAP_DIR}

   ${MKDIR} ${LINUX_APPLICATIONS_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/*.desktop       ${LINUX_APPLICATIONS_DIR}
   chmod  644 ${LINUX_APPLICATIONS_DIR}/*.desktop

   ${MKDIR} ${USBDM_RULESDIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/usbdm.rules      ${USBDM_RULESDIR}/46-usbdm.rules
   chmod  644 ${USBDM_RULESDIR}/46-usbdm.rules
   
   ${MKDIR} ${USBDM_SHARED_DOC_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/changelog.Debian.gz   ${USBDM_SHARED_DOC_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/copyright             ${USBDM_SHARED_DOC_DIR}

   ${MKDIR} ${USBDM_SHARED_DIR}
   ${CP} -r "${USBDM_UPDATE_SITE}"                                             ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/WizardPatches"                   ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/DeviceData"                      ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/Stationery"                      ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/Examples"                        ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/FlashImages"                     ${USBDM_SHARED_DIR}
   ${CP} -r "${SOURCE_DIRECTORY}/PackageFiles/LaunchConfig"                    ${USBDM_SHARED_DIR}

   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/Miscellaneous/nano.specs           ${USBDM_SHARED_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/Miscellaneous/*.xlkr               ${USBDM_SHARED_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/Miscellaneous/error.wav            ${USBDM_SHARED_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/TryProgrammer   ${USBDM_SHARED_DIR} 
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/usbdm.rules     ${USBDM_SHARED_DIR}
   ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/Scripts/*.tcl                      ${USBDM_SHARED_DIR}

   find ${USBDM_SHARED_DIR} -type d -exec chmod 755 {} \;
   find ${USBDM_SHARED_DIR} -type f -exec chmod 644 {} \;
   chmod -f 755 ${USBDM_SHARED_DIR}/TryProgrammer

   ${MKDIR} ${USBDM_LIBDIR}
   ${CP} -r -P "${USBDM_SOURCE_LIBDIR}"/*      ${USBDM_LIBDIR}
   #${RM} ${USBDM_LIBDIR}/*-debug*
   chmod 644 ${USBDM_LIBDIR}/*

   if [[ (${BITNESS} == "64") && -e ${USBDM_SOURCE_LIBDIR32} ]]; then
      # Include i386 version for Codewarrior
      echo "Doing i386 libs"

      I386_LIBS="libusbdm-jni.so libusbdm.so libusbdm-jni-debug.so libusbdm-debug.so"

      ${MKDIR} ${USBDM_LIBDIR}

      for I386_LIB in ${I386_LIBS}; do
         echo "Copying '${I386_LIB}'"
         ${CP}v "${USBDM_SOURCE_LIBDIR32}/${I386_LIB}"* ${USBDM_LIBDIR}   
      done
      chmod 644  ${USBDM_LIBDIR}/*
   fi

   ${MKDIR} ${USBDM_BINDIR}
   ${CP} -r "${USBDM_SOURCE_BINDIR}"/*      ${USBDM_BINDIR}
   # Remove debug and test files
   ${RM} ${USBDM_BINDIR}/CopyFlash
   ${RM} ${USBDM_BINDIR}/*TestImage
   ${RM} ${USBDM_BINDIR}/*Example*   
#   ${RM} ${USBDM_BINDIR}/*-debug
   ${RM} ${USBDM_BINDIR}/Test*
   chmod 755  ${USBDM_BINDIR}/*

   ${MKDIR} ${USBDM_MANUAL_DIR}
   #echo ${SOURCE_DIRECTORY}/Documentation/ManPages/*
   for MANPAGE_FILE in ${SOURCE_DIRECTORY}/Documentation/ManPages/*; do   
      ${CP} ${MANPAGE_FILE} ${MANPAGE_FILE}.1
      gzip --best -f ${MANPAGE_FILE}.1
      ${MV} ${MANPAGE_FILE}.1.gz ${USBDM_MANUAL_DIR}
   done
   chmod 644 ${USBDM_MANUAL_DIR}/* 

   ${MKDIR} ${USBDM_CONTROL_DIR}
   for CONTROL_FILE in postinst prerm; do
      ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/${CONTROL_FILE} ${USBDM_CONTROL_DIR}/${CONTROL_FILE}
      chmod 755 ${USBDM_CONTROL_DIR}/${CONTROL_FILE} 
   done

  case "${MULTIARCH}" in
      i386-linux-gnu)
         ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/control.i386  ${USBDM_CONTROL_DIR}/control
         ;;
      x86_64-linux-gnu)
         ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/control.amd64 ${USBDM_CONTROL_DIR}/control
         ;;
      arm-linux-gnueabihf)
        ${CP} "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/control.armhf ${USBDM_CONTROL_DIR}/control
        ;;
   esac
   chmod 755 ${USBDM_CONTROL_DIR}/control 

   find ${DUMMY_ROOT}   -type d -exec chmod 755 {} \;
   find ${USBDM_LIBDIR} -type f -executable -exec chmod 755 {} \; -exec strip {} \;
   find ${USBDM_LIBDIR} -type f -name \*.so\* -exec chmod 644 {} \;
   find ${DUMMY_ROOT}   -type f ! -executable -exec chmod 644 {} \;

   echo fakeroot dpkg-deb --build ${DUMMY_ROOT}
   fakeroot dpkg-deb --build ${DUMMY_ROOT}

#   echo lintian ${DUMMY_ROOT}.deb   
#   lintian ${DUMMY_ROOT}.deb 
}

# Build for native ARCH
echo "========================================="
echo "Building `getconf LONG_BIT` version"
echo "========================================="
makeDebFile `getconf LONG_BIT`

if [ $? -eq 0 ]
then
  echo "makeDebFile successfully completed"
  pausing
  exit 0
else
  echo "makeDebFile failed" >&2
  read -p "Press any key to continue... " -n1 -s  exit 1
  exit 1
fi



# Build for i386 on x86_64 platform
#if [ `getconf LONG_BIT` != 32 ]; then
#   echo "========================================="
#   echo "Building 32 version on x86_64 platform"
#   echo "========================================="
#   makeDebFile 32
#fi

