#!/bin/bash

SOURCE_DIRECTORY="$(dirname $(readlink -f $0))"

echo Make sure you SOURCE this file!!

echo  "export LD_LIBRARY_PATH=${SOURCE_DIRECTORY}/Tests"
export LD_LIBRARY_PATH=${SOURCE_DIRECTORY}/Tests

