#!/bin/bash

gksudo apt-get install git  
git clone https://github.com/podonoghue/usbdm-eclipse-makefiles-build.git  
git clone https://github.com/podonoghue/usbdm-eclipse-plugins.git  
cd usbdm-eclipse-makefiles-build  
sudo ./LinuxPackages  
./MakeAll  
./CreateDebFile  
sudo ./Update  
