#!/bin/bash
# Packages required for building under linux
# ====================================================

echo This installs the packages to build USBDM
echo

if [ "$1" == "" ]; then
   BITNESS=`getconf LONG_BIT`
   echo "Native ${BITNESS} bit"
elif [ "$1" == "32" ]; then
   BITNESS=32
   echo "${BITNESS} bit"
elif [ "$1" == "64" ]; then
   BITNESS=64
   echo "${BITNESS} bit"
else
   echo "Usage $0 [32|64]"
fi

#exit

if [ "${BITNESS}" == "32" ]; then
# 32-bit build
# =====================================================
sudo apt-get update
sudo apt-get -y install libusb-1.0-0-dev
sudo apt-get -y install tcl8.6-dev
sudo apt-get -y install tcl8.6
sudo apt-get -y install libxerces-c-dev
sudo apt-get -y install libwxgtk3.0-dev
sudo apt-get -y install libwxbase3.0-dev
sudo apt-get -y install g++
sudo apt-get -y install openjdk-8-jdk
sudo apt-get -y install libusb-1.0-0
sudo apt-get -y install default-jdk

elif [ "${BITNESS}" == "64" ]; then
# 64-bit build
# =====================================================
sudo apt-get update
sudo apt-get -y install libusb-1.0-0-dev
sudo apt-get -y install tcl8.6-dev
sudo apt-get -y install tcl8.6
sudo apt-get -y install libxerces-c-dev
sudo apt-get -y install libwxgtk3.0-dev
sudo apt-get -y install libwxbase3.0-dev
sudo apt-get -y install g++
sudo apt-get -y install openjdk-8-jdk
sudo apt-get -y install libusb-1.0-0
sudo apt-get -y install default-jdk

fi


