#!/bin/bash

# Build with native BITNESS

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Building in ${HOME_DIR}"
pushd ${HOME_DIR}

OS=linux
export OS

clear

# Do 64-bit builds
echo make -f Makefile-x64.mk all BITNESS=64
make -f Makefile-x64.mk all BITNESS=64

echo
echo "Finished Buid"
read -p "Press enter"
