#!/bin/bash

# Build with native BITNESS
echo make -f Makefile all
make -f Makefile.mk all

# Uncomment to build 32-bit binaries on linux 64-bit
#echo make -f Makefile all BITNESS=32
#make -f Makefile all BITNESS=32

