#!/bin/bash

# Build with native BITNESS

clear

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Building in ${HOME_DIR}"
pushd ${HOME_DIR}

OS=linux
export OS

pausing() {
   x=5
   echo -n Pausing ...
   while [ $x -gt 0 ];  do
      sleep 1s
      echo -n " $x"
      x=$(( $x - 1 ))
   done
   echo 
}

# Do 64-bit builds
echo make -f Makefile-x64.mk all BITNESS=64
make -f Makefile-x64.mk all BITNESS=64

if [ $? -eq 0 ]
then
  echo "Make successfully completed"
  pausing
  exit 0
else
  echo "Make failed" >&2
  read -p "Press any key to continue... " -n1 -s  exit 1
  exit 1
fi
