#!/bin/bash

# Version Information
MAJOR=4
MINOR=12
MICRO=1
NANO=150
DEBIAN_VERSION=1
VERSION=${MAJOR}.${MINOR}.${MICRO}.${NANO}

MULTIARCH=`gcc --print-multiarch`
ARCH=`uname -n`

BITNESS=`getconf LONG_BIT`

# Where to construct the install tree
PACKAGE_FILE="../usbdm_${VERSION}-${DEBIAN_VERSION}-${ARCH}.deb"

echo "Removing usbdm"
sudo apt-get -y remove usbdm

echo "Installing ${PACKAGE_FILE}"
sudo dpkg -i ${PACKAGE_FILE}

