/**
 * @file    fonts.h
 * @brief   Fonts for LCD
 */
#ifndef SOURCES_FONTS_H_
#define SOURCES_FONTS_H_

#include <stdint.h>
 /*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
namespace USBDM {

/**
 * Represents a simple font
 */
class Font {

public:
   const uint8_t width;          // Width of the character in pixels
   const uint8_t height;         // Height of the character in pixels
   const uint8_t bytesPerChar;   // Bytes used for each character in data table

   const uint8_t *const data;    // Data describing the character pixels
};

/** Small 6x8 font */
extern Font smallFont;
/** Medium 8x8 font */
extern Font mediumFont;
/** Large 8x16 font */
extern Font largeFont;

}; // end namespace USBDM

#endif /* SOURCES_FONTS_H_ */

