@echo off
cls
rem ***  Paths to various things
set VERSION_NUMBER=4
set VERSION_MINOR_NUMBER=11
set VERSION_SUFFIX=_V%VERSION_NUMBER%
set VERSION_MINOR_SUFFIX=_V%VERSION_NUMBER%_%VERSION_MINOR_NUMBER%

set WIN_RAR=c:\Program Files\WinRAR\rar.exe
set INSTALLATION_DIR=Installation
set DOCUMENTATION_INSTALLATION_DIR=%INSTALLATION_DIR%\Documentation
set WIN32_APPLICATION_DIR=%INSTALLATION_DIR%
set BIN_DIR=%WIN32_APPLICATION_DIR%\bin
set WIN32_DRIVER_DIR=%INSTALLATION_DIR%\WinDrivers

copy "%WIN32_APPLICATION_DIR%\wix\"*.msi
copy "%WIN32_DRIVER_DIR%\"*.msi

:allDone
rem pause
