#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Working in "${HOME_DIR}""
cd ${HOME_DIR}

#exit

read -d '' FROMx <<EOF 
\<aliasOption key=\"=_scgc_clock\" locked=\"false\" condition=\"_scgc_clock\" /\>
EOF

read -d '' TOx <<EOF 
      \<aliasOption key=\"=_scgc_clock\" locked=\"false\" condition=\"_scgc_clock\" /\>\\\n\
      \<for keys=\"v\" values=\"=/SIM/\$(_Class)ExternalItems\" condition=\"/SIM/\$(_Class)ExternalItems\" >\\\n\
         <aliasOption key=\"/SIM/%(v)\"           optional=\"true\" locked=\"false\" /\>\\\n\
      \</for\> 
EOF

#FROM='<name>PIT\([0-9]\)'
#TO='<name>PIT_CH\1'

FROM='PIT_CH'
TO='PIT_Ch'

echo from "${FROM}"
echo to "${TO}"

echo starting
rm -r new
mkdir new

for filename in *.svd.xml; do
   #echo sed  "s#${FROM}#${TO}#g" "${filename}" "new/${filename}"
   sed  "s#${FROM}#${TO}#g" "${filename}" >"new/${filename}"
done

