/**
 * @file      hardware.cpp (generated from MK20D5.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin declarations for FRDM_K20D5
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

namespace USBDM {

struct PinInit {
   uint32_t pcrValue;
   uint32_t volatile *pcr;
};

static constexpr PinInit pinInit[] = {
 /* PTA0       ==> JTAG_TCLK/SWD_CLK              */  { PORT_PCR_MUX(7)|USBDM::DEFAULT_PCR, &PORTA->PCR[0],  },
 /* PTA1       ==> FTM0_CH6                       */  { PORT_PCR_MUX(3)|USBDM::DEFAULT_PCR, &PORTA->PCR[1],  },
 /* PTA2       ==> GPIOA_2                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[2],  },
 /* PTA3       ==> JTAG_TMS/SWD_DIO               */  { PORT_PCR_MUX(7)|USBDM::DEFAULT_PCR, &PORTA->PCR[3],  },
 /* PTA4       ==> GPIOA_4/LLWU_P3                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[4],  },
 /* PTA5       ==> GPIOA_5                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[5],  },
 /* PTA12      ==> GPIOA_12                       */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[12], },
 /* PTA13      ==> GPIOA_13/LLWU_P4               */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[13], },
 /* PTA18      ==> EXTAL0                         */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTA->PCR[18], },
 /* PTA19      ==> XTAL0                          */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTA->PCR[19], },
 /* PTB0       ==> GPIOB_0/LLWU_P5                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTB->PCR[0],  },
 /* PTB1       ==> GPIOB_1                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTB->PCR[1],  },
 /* PTB2       ==> GPIOB_2                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTB->PCR[2],  },
 /* PTB3       ==> GPIOB_3                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTB->PCR[3],  },
 /* PTB16      ==> UART0_RX                       */  { PORT_PCR_MUX(3)|USBDM::DEFAULT_PCR, &PORTB->PCR[16], },
 /* PTB17      ==> UART0_TX                       */  { PORT_PCR_MUX(3)|USBDM::DEFAULT_PCR, &PORTB->PCR[17], },
 /* PTB18      ==> TSI0_CH11                      */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTB->PCR[18], },
 /* PTB19      ==> TSI0_CH12                      */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTB->PCR[19], },
 /* PTC0       ==> ADC0_SE14/TSI0_CH13            */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTC->PCR[0],  },
 /* PTC1       ==> ADC0_SE15/TSI0_CH14            */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTC->PCR[1],  },
 /* PTC2       ==> GPIOC_2                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[2],  },
 /* PTC3       ==> GPIOC_3/LLWU_P7                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[3],  },
 /* PTC4       ==> GPIOC_4/LLWU_P8                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[4],  },
 /* PTC5       ==> GPIOC_5/LLWU_P9                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[5],  },
 /* PTC6       ==> GPIOC_6/LLWU_P10               */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[6],  },
 /* PTC7       ==> GPIOC_7                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[7],  },
 /* PTC8       ==> GPIOC_8                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[8],  },
 /* PTC9       ==> GPIOC_9                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[9],  },
 /* PTC10      ==> GPIOC_10                       */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[10], },
 /* PTC11      ==> GPIOC_11/LLWU_P11              */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTC->PCR[11], },
 /* PTD0       ==> GPIOD_0/LLWU_P12               */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTD->PCR[0],  },
 /* PTD1       ==> SPI0_SCK                       */  { PORT_PCR_MUX(2)|USBDM::DEFAULT_PCR, &PORTD->PCR[1],  },
 /* PTD2       ==> SPI0_SOUT                      */  { PORT_PCR_MUX(2)|USBDM::DEFAULT_PCR, &PORTD->PCR[2],  },
 /* PTD3       ==> SPI0_SIN                       */  { PORT_PCR_MUX(2)|USBDM::DEFAULT_PCR, &PORTD->PCR[3],  },
 /* PTD4       ==> GPIOD_4/LLWU_P14               */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTD->PCR[4],  },
 /* PTD5       ==> ADC0_SE6b                      */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTD->PCR[5],  },
 /* PTD6       ==> ADC0_SE7b                      */  { PORT_PCR_MUX(0)|USBDM::DEFAULT_PCR, &PORTD->PCR[6],  },
 /* PTD7       ==> GPIOD_7                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTD->PCR[7],  },
 /* PTE0       ==> GPIOE_0                        */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTE->PCR[0],  },
 /* PTE1       ==> GPIOE_1/LLWU_P0                */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTE->PCR[1],  },
};

/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {

   SIM->FIXED_PORT_CLOCK_REG |= PORTA_CLOCK_MASK|PORTB_CLOCK_MASK|PORTC_CLOCK_MASK|PORTD_CLOCK_MASK|PORTE_CLOCK_MASK;

   for (const PinInit *p=pinInit; p<(pinInit+(sizeof(pinInit)/sizeof(pinInit[0]))); p++) {
      *(p->pcr) = p->pcrValue;
   }
}

} // End namespace USBDM
