/**
 * @file      hardware.cpp (generated from MKL27Z644.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin declarations for FRDM_KL27Z
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

namespace USBDM {

/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {
      enablePortClocks(PORTA_CLOCK_MASK|PORTB_CLOCK_MASK|PORTC_CLOCK_MASK|PORTD_CLOCK_MASK|PORTE_CLOCK_MASK);

      ((PORT_Type *)PORTA_BasePtr)->GPCLR = 0x0100UL|PORT_GPCLR_GPWE(0x3020UL);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = 0x0200UL|PORT_GPCLR_GPWE(0x0006UL);
      ((PORT_Type *)PORTB_BasePtr)->GPCLR = 0x0000UL|PORT_GPCLR_GPWE(0x0003UL);
      ((PORT_Type *)PORTB_BasePtr)->GPCHR = 0x0100UL|PORT_GPCHR_GPWE(0x000CUL);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = 0x0000UL|PORT_GPCLR_GPWE(0x0001UL);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = 0x0100UL|PORT_GPCLR_GPWE(0x03F0UL);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = 0x0500UL|PORT_GPCLR_GPWE(0x0008UL);
      ((PORT_Type *)PORTD_BasePtr)->GPCLR = 0x0400UL|PORT_GPCLR_GPWE(0x00C0UL);
      ((PORT_Type *)PORTE_BasePtr)->GPCHR = 0x0000UL|PORT_GPCHR_GPWE(0x0031UL);
      ((PORT_Type *)PORTE_BasePtr)->GPCHR = 0x0100UL|PORT_GPCHR_GPWE(0x8300UL);
}

} // End namespace USBDM

