#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Working in "${HOME_DIR}""
cd ${HOME_DIR}

#exit

FROM="<name>INT</name>"
TO="<name>INTV</name>"

echo starting
rm -r new
mkdir new

for filename in PDB*.svd.xml; do
   echo sed  "s%${FROM}%${TO}%g" "${filename}" "new/${filename}"
   sed  "s%${FROM}%${TO}%g" "${filename}" >"new/${filename}"
done

