#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Working in "${HOME_DIR}""
cd ${HOME_DIR}

#exit

FROM="<name>I2S<"
TO="<name>I2S0<"

echo starting
rm -r new
mkdir new

for filename in SIM*.svd.xml; do
   echo sed  "s/${FROM}/${TO}/g" "${filename}" "new/${filename}"
   sed  "s/${FROM}/${TO}/g" "${filename}" >"new/${filename}"
done

