#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo "Working in "${HOME_DIR}""
cd ${HOME_DIR}

#exit

FROM="<addressOffset>0xC"
TO="<addressOffset>0x9"

echo starting
rm -r new
mkdir new

for filename in UART*.svd.xml; do
   echo sed  "s/${FROM}/${TO}/g" "${filename}" "new/${filename}"
   sed  "s/${FROM}/${TO}/g" "${filename}" >"new/${filename}"
done

