/*
 * cr20a.h
 *
 *  Created on: 27Oct.,2017
 *      Author: podonoghue
 */

#ifndef SOURCES_CR20A_H_
#define SOURCES_CR20A_H_

static constexpr uint8_t REGISTER_READ             = 0b10000000;
static constexpr uint8_t REGISTER_WRITE            = 0b00000000;
static constexpr uint8_t PKT_BUFFER_BURST_READ     = 0b11000000;
static constexpr uint8_t PKT_BUFFER_BURST_WRITE    = 0b01000000;
//static constexpr uint8_t PKT_BUFFER_BYTE_READ      = 0b11100000;
//static constexpr uint8_t PKT_BUFFER_BYTE_WRITE     = 0b01100000;

enum ModemReg {
   ModemReg_IRQSTS1              = 0x00,
   ModemReg_IRQSTS2              = 0x01,
   ModemReg_IRQSTS3              = 0x02,
   ModemReg_PHY_CTRL1            = 0x03,
   ModemReg_PHY_CTRL2            = 0x04,
   ModemReg_PHY_CTRL3            = 0x05,
   ModemReg_RX_FRM_LEN           = 0x06,
   ModemReg_PHY_CTRL4            = 0x07,
   ModemReg_SRC_CTRL             = 0x08,
   ModemReg_SRC_ADDRS_SUM_LSB    = 0x09,
   ModemReg_SRC_ADDRS_SUM_MSB    = 0x0A,
   ModemReg_CCA1_ED_FNL          = 0x0B,
   ModemReg_EVENT_TIMER_LSB      = 0x0C,
   ModemReg_EVENT_TIMER_MSB      = 0x0D,
   ModemReg_EVENT_TIMER_USB      = 0x0E,
   ModemReg_TIMESTAMP_LSB        = 0x0F,
   ModemReg_TIMESTAMP_MSB        = 0x10,
   ModemReg_TIMESTAMP_USB        = 0x11,
   ModemReg_T3CMP_LSB            = 0x12,
   ModemReg_T3CMP_MSB            = 0x13,
   ModemReg_T3CMP_USB            = 0x14,
   ModemReg_T2PRIMECMP_LSB       = 0x15,
   ModemReg_T2PRIMECMP_MSB       = 0x16,
   ModemReg_T1CMP_LSB            = 0x17,
   ModemReg_T1CMP_MSB            = 0x18,
   ModemReg_T1CMP_USB            = 0x19,
   ModemReg_T2CMP_LSB            = 0x1A,
   ModemReg_T2CMP_MSB            = 0x1B,
   ModemReg_T2CMP_USB            = 0x1C,
   ModemReg_T4CMP_LSB            = 0x1D,
   ModemReg_T4CMP_MSB            = 0x1E,
   ModemReg_T4CMP_USB            = 0x1F,
   ModemReg_PLL_INT0             = 0x20,
   ModemReg_PLL_FRAC0_LSB        = 0x21,
   ModemReg_PLL_FRAC0_MSB        = 0x22,
   ModemReg_PA_PWR               = 0x23,
   ModemReg_SEQ_STATE            = 0x24,
   ModemReg_LQI_VALUE            = 0x25,
   ModemReg_RSSI_CCA_CNT         = 0x26,
   ModemReg_ASM_CTRL1            = 0x28,
   ModemReg_ASM_CTRL2            = 0x29,
   ModemReg_ASM_DATA_0           = 0x2A,
   ModemReg_ASM_DATA_1           = 0x2B,
   ModemReg_ASM_DATA_2           = 0x2C,
   ModemReg_ASM_DATA_3           = 0x2D,
   ModemReg_ASM_DATA_4           = 0x2E,
   ModemReg_ASM_DATA_5           = 0x2F,
   ModemReg_ASM_DATA_6           = 0x30,
   ModemReg_ASM_DATA_7           = 0x31,
   ModemReg_ASM_DATA_8           = 0x32,
   ModemReg_ASM_DATA_9           = 0x33,
   ModemReg_ASM_DATA_A           = 0x34,
   ModemReg_ASM_DATA_B           = 0x35,
   ModemReg_ASM_DATA_C           = 0x36,
   ModemReg_ASM_DATA_D           = 0x37,
   ModemReg_ASM_DATA_E           = 0x38,
   ModemReg_ASM_DATA_F           = 0x39,
   ModemReg_OVERWRITE_VER        = 0x3B,
   ModemReg_CLK_OUT_CTRL         = 0x3C,
   ModemReg_PWR_MODES            = 0x3D,
   ModemReg_IAR_INDEX            = 0x3E,
   ModemReg_IAR_DATA             = 0x3F,
};

enum ModemIndirectReg {
   ModemIndirectReg_PART_ID             = 0x00,
   ModemIndirectReg_XTAL_TRIM           = 0x01,
   ModemIndirectReg_MACPANID0_LSB       = 0x03,
   ModemIndirectReg_MACPANID0_MSB       = 0x04,
   ModemIndirectReg_MACSHORTADDRS0_LSB  = 0x05,
   ModemIndirectReg_MACSHORTADDRS0_MSB  = 0x06,
   ModemIndirectReg_MACLONGADDRS0_0     = 0x07,
   ModemIndirectReg_MACLONGADDRS0_1     = 0x08,
   ModemIndirectReg_MACLONGADDRS0_2     = 0x09,
   ModemIndirectReg_MACLONGADDRS0_3     = 0x0A,
   ModemIndirectReg_MACLONGADDRS0_4     = 0x0B,
   ModemIndirectReg_MACLONGADDRS0_5     = 0x0C,
   ModemIndirectReg_MACLONGADDRS0_6     = 0x0D,
   ModemIndirectReg_MACLONGADDRS0_7     = 0x0E,
   ModemIndirectReg_RX_FRAME_FILTER     = 0x0F,
   ModemIndirectReg_PLL_INT1            = 0x10,
   ModemIndirectReg_PLL_FRAC1_LSB       = 0x11,
   ModemIndirectReg_PLL_FRAC1_MSB       = 0x12,
   ModemIndirectReg_MACPANID1_LSB       = 0x13,
   ModemIndirectReg_MACPANID1_MSB       = 0x14,
   ModemIndirectReg_MACSHORTADDRS1_LSB  = 0x15,
   ModemIndirectReg_MACSHORTADDRS1_MSB  = 0x16,
   ModemIndirectReg_MACLONGADDRS1_0     = 0x17,
   ModemIndirectReg_MACLONGADDRS1_1     = 0x18,
   ModemIndirectReg_MACLONGADDRS1_2     = 0x19,
   ModemIndirectReg_MACLONGADDRS1_3     = 0x1A,
   ModemIndirectReg_MACLONGADDRS1_4     = 0x1B,
   ModemIndirectReg_MACLONGADDRS1_5     = 0x1C,
   ModemIndirectReg_MACLONGADDRS1_6     = 0x1D,
   ModemIndirectReg_MACLONGADDRS1_7     = 0x1E,
   ModemIndirectReg_DUAL_PAN_CTRL       = 0x1F,
   ModemIndirectReg_DUAL_PAN_DWELL      = 0x20,
   ModemIndirectReg_DUAL_PAN_STS        = 0x21,
   ModemIndirectReg_CCA1_THRESH         = 0x22,
   ModemIndirectReg_CCA1_ED_OFFSET_COMP = 0x23,
   ModemIndirectReg_LQI_OFFSET_COMP     = 0x24,
   ModemIndirectReg_CCA_CTRL            = 0x25,
   ModemIndirectReg_CCA2_CORR_PEAKS     = 0x26,
   ModemIndirectReg_CCA2_THRESH         = 0x27,
   ModemIndirectReg_TMR_PRESCALE        = 0x28,
   ModemIndirectReg_GPIO_DATA           = 0x2A,
   ModemIndirectReg_GPIO_DIR            = 0x2B,
   ModemIndirectReg_GPIO_PUL_EN         = 0x2C,
   ModemIndirectReg_GPIO_SEL            = 0x2D,
   ModemIndirectReg_GPIO_DS             = 0x2E,
   ModemIndirectReg_ANT_PAD_CTRL        = 0x30,
   ModemIndirectReg_MISC_PAD_CTRL       = 0x31,
   ModemIndirectReg_RX_BYTE_COUNT       = 0x35,
   ModemIndirectReg_RX_WTR_MARK         = 0x36,
   ModemIndirectReg_TXDELAY             = 0x38,
   ModemIndirectReg_ACKDELAY            = 0x39,
   ModemIndirectReg_ANT_AGC_CTRL        = 0x51,
   ModemIndirectReg_LPPS_CTRL           = 0x56,
   ModemIndirectReg_RSSI                = 0x5B,
   ModemIndirectReg_XTAL_CTRL           = 0x6E,
};

#endif /* SOURCES_CR20A_H_ */
