 /**
  * @file     gpio.cpp (from gpio-MKM33Z5.cpp)
  *
  * @brief   Pin declarations for MKM33Z5
  */

#include "utilities.h"
#include "gpio.h"
#include "pin_mapping.h"

/**
 * @brief Create ADC Clock register name from ADC number
 *
 * @param number Timer number e.g. 1 => ADC1_CLOCK_REG
 */
#define ADC_CLOCK_REG(number)  CONCAT3_(ADC,number,_CLOCK_REG)

/**
 * @brief Create ADC Clock register mask from ADC number
 *
 * @param number Timer number e.g. 1 => ADC1_CLOCK_MASK
 */
#define ADC_CLOCK_MASK(number)  CONCAT3_(ADC,number,_CLOCK_MASK)

#define ADC(num)             CONCAT2_(ADC,num)   
#define FTM(num)             CONCAT2_(FTM,num)   
#define TPM(num)             CONCAT2_(TPM,num)   

const DigitalIO digitalIO_PTA0     = {&PCR(PTA0_GPIO_NAME,PTA0_GPIO_BIT),GPIO(PTA0_GPIO_NAME),PORT_CLOCK_MASK(PTA0_GPIO_NAME),(1UL<<PTA0_GPIO_BIT)};
const DigitalIO digitalIO_PTA1     = {&PCR(PTA1_GPIO_NAME,PTA1_GPIO_BIT),GPIO(PTA1_GPIO_NAME),PORT_CLOCK_MASK(PTA1_GPIO_NAME),(1UL<<PTA1_GPIO_BIT)};
const DigitalIO digitalIO_PTA2     = {&PCR(PTA2_GPIO_NAME,PTA2_GPIO_BIT),GPIO(PTA2_GPIO_NAME),PORT_CLOCK_MASK(PTA2_GPIO_NAME),(1UL<<PTA2_GPIO_BIT)};
const DigitalIO digitalIO_PTA3     = {&PCR(PTA3_GPIO_NAME,PTA3_GPIO_BIT),GPIO(PTA3_GPIO_NAME),PORT_CLOCK_MASK(PTA3_GPIO_NAME),(1UL<<PTA3_GPIO_BIT)};
const DigitalIO digitalIO_PTA4     = {&PCR(PTA4_GPIO_NAME,PTA4_GPIO_BIT),GPIO(PTA4_GPIO_NAME),PORT_CLOCK_MASK(PTA4_GPIO_NAME),(1UL<<PTA4_GPIO_BIT)};
const DigitalIO digitalIO_PTA5     = {&PCR(PTA5_GPIO_NAME,PTA5_GPIO_BIT),GPIO(PTA5_GPIO_NAME),PORT_CLOCK_MASK(PTA5_GPIO_NAME),(1UL<<PTA5_GPIO_BIT)};
const DigitalIO digitalIO_PTA6     = {&PCR(PTA6_GPIO_NAME,PTA6_GPIO_BIT),GPIO(PTA6_GPIO_NAME),PORT_CLOCK_MASK(PTA6_GPIO_NAME),(1UL<<PTA6_GPIO_BIT)};
const DigitalIO digitalIO_PTA7     = {&PCR(PTA7_GPIO_NAME,PTA7_GPIO_BIT),GPIO(PTA7_GPIO_NAME),PORT_CLOCK_MASK(PTA7_GPIO_NAME),(1UL<<PTA7_GPIO_BIT)};
const DigitalIO digitalIO_PTB0     = {&PCR(PTB0_GPIO_NAME,PTB0_GPIO_BIT),GPIO(PTB0_GPIO_NAME),PORT_CLOCK_MASK(PTB0_GPIO_NAME),(1UL<<PTB0_GPIO_BIT)};
const DigitalIO digitalIO_PTB1     = {&PCR(PTB1_GPIO_NAME,PTB1_GPIO_BIT),GPIO(PTB1_GPIO_NAME),PORT_CLOCK_MASK(PTB1_GPIO_NAME),(1UL<<PTB1_GPIO_BIT)};
const DigitalIO digitalIO_PTB2     = {&PCR(PTB2_GPIO_NAME,PTB2_GPIO_BIT),GPIO(PTB2_GPIO_NAME),PORT_CLOCK_MASK(PTB2_GPIO_NAME),(1UL<<PTB2_GPIO_BIT)};
const DigitalIO digitalIO_PTB3     = {&PCR(PTB3_GPIO_NAME,PTB3_GPIO_BIT),GPIO(PTB3_GPIO_NAME),PORT_CLOCK_MASK(PTB3_GPIO_NAME),(1UL<<PTB3_GPIO_BIT)};
const DigitalIO digitalIO_PTB4     = {&PCR(PTB4_GPIO_NAME,PTB4_GPIO_BIT),GPIO(PTB4_GPIO_NAME),PORT_CLOCK_MASK(PTB4_GPIO_NAME),(1UL<<PTB4_GPIO_BIT)};
const DigitalIO digitalIO_PTB5     = {&PCR(PTB5_GPIO_NAME,PTB5_GPIO_BIT),GPIO(PTB5_GPIO_NAME),PORT_CLOCK_MASK(PTB5_GPIO_NAME),(1UL<<PTB5_GPIO_BIT)};
const DigitalIO digitalIO_PTB6     = {&PCR(PTB6_GPIO_NAME,PTB6_GPIO_BIT),GPIO(PTB6_GPIO_NAME),PORT_CLOCK_MASK(PTB6_GPIO_NAME),(1UL<<PTB6_GPIO_BIT)};
const DigitalIO digitalIO_PTB7     = {&PCR(PTB7_GPIO_NAME,PTB7_GPIO_BIT),GPIO(PTB7_GPIO_NAME),PORT_CLOCK_MASK(PTB7_GPIO_NAME),(1UL<<PTB7_GPIO_BIT)};
const DigitalIO digitalIO_PTC0     = {&PCR(PTC0_GPIO_NAME,PTC0_GPIO_BIT),GPIO(PTC0_GPIO_NAME),PORT_CLOCK_MASK(PTC0_GPIO_NAME),(1UL<<PTC0_GPIO_BIT)};
const DigitalIO digitalIO_PTC1     = {&PCR(PTC1_GPIO_NAME,PTC1_GPIO_BIT),GPIO(PTC1_GPIO_NAME),PORT_CLOCK_MASK(PTC1_GPIO_NAME),(1UL<<PTC1_GPIO_BIT)};
const DigitalIO digitalIO_PTC2     = {&PCR(PTC2_GPIO_NAME,PTC2_GPIO_BIT),GPIO(PTC2_GPIO_NAME),PORT_CLOCK_MASK(PTC2_GPIO_NAME),(1UL<<PTC2_GPIO_BIT)};
const DigitalIO digitalIO_PTC3     = {&PCR(PTC3_GPIO_NAME,PTC3_GPIO_BIT),GPIO(PTC3_GPIO_NAME),PORT_CLOCK_MASK(PTC3_GPIO_NAME),(1UL<<PTC3_GPIO_BIT)};
const DigitalIO digitalIO_PTC4     = {&PCR(PTC4_GPIO_NAME,PTC4_GPIO_BIT),GPIO(PTC4_GPIO_NAME),PORT_CLOCK_MASK(PTC4_GPIO_NAME),(1UL<<PTC4_GPIO_BIT)};
const DigitalIO digitalIO_PTC5     = {&PCR(PTC5_GPIO_NAME,PTC5_GPIO_BIT),GPIO(PTC5_GPIO_NAME),PORT_CLOCK_MASK(PTC5_GPIO_NAME),(1UL<<PTC5_GPIO_BIT)};
const DigitalIO digitalIO_PTC6     = {&PCR(PTC6_GPIO_NAME,PTC6_GPIO_BIT),GPIO(PTC6_GPIO_NAME),PORT_CLOCK_MASK(PTC6_GPIO_NAME),(1UL<<PTC6_GPIO_BIT)};
const DigitalIO digitalIO_PTC7     = {&PCR(PTC7_GPIO_NAME,PTC7_GPIO_BIT),GPIO(PTC7_GPIO_NAME),PORT_CLOCK_MASK(PTC7_GPIO_NAME),(1UL<<PTC7_GPIO_BIT)};
const DigitalIO digitalIO_PTD0     = {&PCR(PTD0_GPIO_NAME,PTD0_GPIO_BIT),GPIO(PTD0_GPIO_NAME),PORT_CLOCK_MASK(PTD0_GPIO_NAME),(1UL<<PTD0_GPIO_BIT)};
const DigitalIO digitalIO_PTD1     = {&PCR(PTD1_GPIO_NAME,PTD1_GPIO_BIT),GPIO(PTD1_GPIO_NAME),PORT_CLOCK_MASK(PTD1_GPIO_NAME),(1UL<<PTD1_GPIO_BIT)};
const DigitalIO digitalIO_PTD2     = {&PCR(PTD2_GPIO_NAME,PTD2_GPIO_BIT),GPIO(PTD2_GPIO_NAME),PORT_CLOCK_MASK(PTD2_GPIO_NAME),(1UL<<PTD2_GPIO_BIT)};
const DigitalIO digitalIO_PTD3     = {&PCR(PTD3_GPIO_NAME,PTD3_GPIO_BIT),GPIO(PTD3_GPIO_NAME),PORT_CLOCK_MASK(PTD3_GPIO_NAME),(1UL<<PTD3_GPIO_BIT)};
const DigitalIO digitalIO_PTD4     = {&PCR(PTD4_GPIO_NAME,PTD4_GPIO_BIT),GPIO(PTD4_GPIO_NAME),PORT_CLOCK_MASK(PTD4_GPIO_NAME),(1UL<<PTD4_GPIO_BIT)};
const DigitalIO digitalIO_PTD5     = {&PCR(PTD5_GPIO_NAME,PTD5_GPIO_BIT),GPIO(PTD5_GPIO_NAME),PORT_CLOCK_MASK(PTD5_GPIO_NAME),(1UL<<PTD5_GPIO_BIT)};
const DigitalIO digitalIO_PTD6     = {&PCR(PTD6_GPIO_NAME,PTD6_GPIO_BIT),GPIO(PTD6_GPIO_NAME),PORT_CLOCK_MASK(PTD6_GPIO_NAME),(1UL<<PTD6_GPIO_BIT)};
const DigitalIO digitalIO_PTD7     = {&PCR(PTD7_GPIO_NAME,PTD7_GPIO_BIT),GPIO(PTD7_GPIO_NAME),PORT_CLOCK_MASK(PTD7_GPIO_NAME),(1UL<<PTD7_GPIO_BIT)};
const DigitalIO digitalIO_PTE0     = {&PCR(PTE0_GPIO_NAME,PTE0_GPIO_BIT),GPIO(PTE0_GPIO_NAME),PORT_CLOCK_MASK(PTE0_GPIO_NAME),(1UL<<PTE0_GPIO_BIT)};
const DigitalIO digitalIO_PTE1     = {&PCR(PTE1_GPIO_NAME,PTE1_GPIO_BIT),GPIO(PTE1_GPIO_NAME),PORT_CLOCK_MASK(PTE1_GPIO_NAME),(1UL<<PTE1_GPIO_BIT)};
const DigitalIO digitalIO_PTE2     = {&PCR(PTE2_GPIO_NAME,PTE2_GPIO_BIT),GPIO(PTE2_GPIO_NAME),PORT_CLOCK_MASK(PTE2_GPIO_NAME),(1UL<<PTE2_GPIO_BIT)};
const DigitalIO digitalIO_PTE3     = {&PCR(PTE3_GPIO_NAME,PTE3_GPIO_BIT),GPIO(PTE3_GPIO_NAME),PORT_CLOCK_MASK(PTE3_GPIO_NAME),(1UL<<PTE3_GPIO_BIT)};
const DigitalIO digitalIO_PTE4     = {&PCR(PTE4_GPIO_NAME,PTE4_GPIO_BIT),GPIO(PTE4_GPIO_NAME),PORT_CLOCK_MASK(PTE4_GPIO_NAME),(1UL<<PTE4_GPIO_BIT)};
const DigitalIO digitalIO_PTE5     = {&PCR(PTE5_GPIO_NAME,PTE5_GPIO_BIT),GPIO(PTE5_GPIO_NAME),PORT_CLOCK_MASK(PTE5_GPIO_NAME),(1UL<<PTE5_GPIO_BIT)};
const DigitalIO digitalIO_PTE6     = {&PCR(PTE6_GPIO_NAME,PTE6_GPIO_BIT),GPIO(PTE6_GPIO_NAME),PORT_CLOCK_MASK(PTE6_GPIO_NAME),(1UL<<PTE6_GPIO_BIT)};
const DigitalIO digitalIO_PTE7     = {&PCR(PTE7_GPIO_NAME,PTE7_GPIO_BIT),GPIO(PTE7_GPIO_NAME),PORT_CLOCK_MASK(PTE7_GPIO_NAME),(1UL<<PTE7_GPIO_BIT)};
const DigitalIO digitalIO_PTF0     = {&PCR(PTF0_GPIO_NAME,PTF0_GPIO_BIT),GPIO(PTF0_GPIO_NAME),PORT_CLOCK_MASK(PTF0_GPIO_NAME),(1UL<<PTF0_GPIO_BIT)};
const DigitalIO digitalIO_PTF1     = {&PCR(PTF1_GPIO_NAME,PTF1_GPIO_BIT),GPIO(PTF1_GPIO_NAME),PORT_CLOCK_MASK(PTF1_GPIO_NAME),(1UL<<PTF1_GPIO_BIT)};
const DigitalIO digitalIO_PTF2     = {&PCR(PTF2_GPIO_NAME,PTF2_GPIO_BIT),GPIO(PTF2_GPIO_NAME),PORT_CLOCK_MASK(PTF2_GPIO_NAME),(1UL<<PTF2_GPIO_BIT)};
const DigitalIO digitalIO_PTF3     = {&PCR(PTF3_GPIO_NAME,PTF3_GPIO_BIT),GPIO(PTF3_GPIO_NAME),PORT_CLOCK_MASK(PTF3_GPIO_NAME),(1UL<<PTF3_GPIO_BIT)};
const DigitalIO digitalIO_PTF4     = {&PCR(PTF4_GPIO_NAME,PTF4_GPIO_BIT),GPIO(PTF4_GPIO_NAME),PORT_CLOCK_MASK(PTF4_GPIO_NAME),(1UL<<PTF4_GPIO_BIT)};
const DigitalIO digitalIO_PTF5     = {&PCR(PTF5_GPIO_NAME,PTF5_GPIO_BIT),GPIO(PTF5_GPIO_NAME),PORT_CLOCK_MASK(PTF5_GPIO_NAME),(1UL<<PTF5_GPIO_BIT)};
const DigitalIO digitalIO_PTF6     = {&PCR(PTF6_GPIO_NAME,PTF6_GPIO_BIT),GPIO(PTF6_GPIO_NAME),PORT_CLOCK_MASK(PTF6_GPIO_NAME),(1UL<<PTF6_GPIO_BIT)};
const DigitalIO digitalIO_PTF7     = {&PCR(PTF7_GPIO_NAME,PTF7_GPIO_BIT),GPIO(PTF7_GPIO_NAME),PORT_CLOCK_MASK(PTF7_GPIO_NAME),(1UL<<PTF7_GPIO_BIT)};
const DigitalIO digitalIO_PTG0     = {&PCR(PTG0_GPIO_NAME,PTG0_GPIO_BIT),GPIO(PTG0_GPIO_NAME),PORT_CLOCK_MASK(PTG0_GPIO_NAME),(1UL<<PTG0_GPIO_BIT)};
const DigitalIO digitalIO_PTG1     = {&PCR(PTG1_GPIO_NAME,PTG1_GPIO_BIT),GPIO(PTG1_GPIO_NAME),PORT_CLOCK_MASK(PTG1_GPIO_NAME),(1UL<<PTG1_GPIO_BIT)};
const DigitalIO digitalIO_PTG2     = {&PCR(PTG2_GPIO_NAME,PTG2_GPIO_BIT),GPIO(PTG2_GPIO_NAME),PORT_CLOCK_MASK(PTG2_GPIO_NAME),(1UL<<PTG2_GPIO_BIT)};
const DigitalIO digitalIO_PTG3     = {&PCR(PTG3_GPIO_NAME,PTG3_GPIO_BIT),GPIO(PTG3_GPIO_NAME),PORT_CLOCK_MASK(PTG3_GPIO_NAME),(1UL<<PTG3_GPIO_BIT)};
const DigitalIO digitalIO_PTG4     = {&PCR(PTG4_GPIO_NAME,PTG4_GPIO_BIT),GPIO(PTG4_GPIO_NAME),PORT_CLOCK_MASK(PTG4_GPIO_NAME),(1UL<<PTG4_GPIO_BIT)};
const DigitalIO digitalIO_PTG5     = {&PCR(PTG5_GPIO_NAME,PTG5_GPIO_BIT),GPIO(PTG5_GPIO_NAME),PORT_CLOCK_MASK(PTG5_GPIO_NAME),(1UL<<PTG5_GPIO_BIT)};
const DigitalIO digitalIO_PTG6     = {&PCR(PTG6_GPIO_NAME,PTG6_GPIO_BIT),GPIO(PTG6_GPIO_NAME),PORT_CLOCK_MASK(PTG6_GPIO_NAME),(1UL<<PTG6_GPIO_BIT)};
const DigitalIO digitalIO_PTG7     = {&PCR(PTG7_GPIO_NAME,PTG7_GPIO_BIT),GPIO(PTG7_GPIO_NAME),PORT_CLOCK_MASK(PTG7_GPIO_NAME),(1UL<<PTG7_GPIO_BIT)};
const DigitalIO digitalIO_PTH0     = {&PCR(PTH0_GPIO_NAME,PTH0_GPIO_BIT),GPIO(PTH0_GPIO_NAME),PORT_CLOCK_MASK(PTH0_GPIO_NAME),(1UL<<PTH0_GPIO_BIT)};
const DigitalIO digitalIO_PTH1     = {&PCR(PTH1_GPIO_NAME,PTH1_GPIO_BIT),GPIO(PTH1_GPIO_NAME),PORT_CLOCK_MASK(PTH1_GPIO_NAME),(1UL<<PTH1_GPIO_BIT)};
const DigitalIO digitalIO_PTH2     = {&PCR(PTH2_GPIO_NAME,PTH2_GPIO_BIT),GPIO(PTH2_GPIO_NAME),PORT_CLOCK_MASK(PTH2_GPIO_NAME),(1UL<<PTH2_GPIO_BIT)};
const DigitalIO digitalIO_PTH3     = {&PCR(PTH3_GPIO_NAME,PTH3_GPIO_BIT),GPIO(PTH3_GPIO_NAME),PORT_CLOCK_MASK(PTH3_GPIO_NAME),(1UL<<PTH3_GPIO_BIT)};
const DigitalIO digitalIO_PTH4     = {&PCR(PTH4_GPIO_NAME,PTH4_GPIO_BIT),GPIO(PTH4_GPIO_NAME),PORT_CLOCK_MASK(PTH4_GPIO_NAME),(1UL<<PTH4_GPIO_BIT)};
const DigitalIO digitalIO_PTH5     = {&PCR(PTH5_GPIO_NAME,PTH5_GPIO_BIT),GPIO(PTH5_GPIO_NAME),PORT_CLOCK_MASK(PTH5_GPIO_NAME),(1UL<<PTH5_GPIO_BIT)};
const DigitalIO digitalIO_PTH6     = {&PCR(PTH6_GPIO_NAME,PTH6_GPIO_BIT),GPIO(PTH6_GPIO_NAME),PORT_CLOCK_MASK(PTH6_GPIO_NAME),(1UL<<PTH6_GPIO_BIT)};
const DigitalIO digitalIO_PTH7     = {&PCR(PTH7_GPIO_NAME,PTH7_GPIO_BIT),GPIO(PTH7_GPIO_NAME),PORT_CLOCK_MASK(PTH7_GPIO_NAME),(1UL<<PTH7_GPIO_BIT)};
const DigitalIO digitalIO_PTI0     = {&PCR(PTI0_GPIO_NAME,PTI0_GPIO_BIT),GPIO(PTI0_GPIO_NAME),PORT_CLOCK_MASK(PTI0_GPIO_NAME),(1UL<<PTI0_GPIO_BIT)};
const DigitalIO digitalIO_PTI1     = {&PCR(PTI1_GPIO_NAME,PTI1_GPIO_BIT),GPIO(PTI1_GPIO_NAME),PORT_CLOCK_MASK(PTI1_GPIO_NAME),(1UL<<PTI1_GPIO_BIT)};
const DigitalIO digitalIO_PTI2     = {&PCR(PTI2_GPIO_NAME,PTI2_GPIO_BIT),GPIO(PTI2_GPIO_NAME),PORT_CLOCK_MASK(PTI2_GPIO_NAME),(1UL<<PTI2_GPIO_BIT)};
const DigitalIO digitalIO_PTI3     = {&PCR(PTI3_GPIO_NAME,PTI3_GPIO_BIT),GPIO(PTI3_GPIO_NAME),PORT_CLOCK_MASK(PTI3_GPIO_NAME),(1UL<<PTI3_GPIO_BIT)};
const AnalogueIO analogueIO_PTC5        = {&digitalIO_PTC5,  ADC(PTC5_ADC_NUM),  &ADC_CLOCK_REG(PTC5_ADC_NUM),  ADC_CLOCK_MASK(PTC5_ADC_NUM),  PTC5_ADC_CH};
const AnalogueIO analogueIO_PTC6        = {&digitalIO_PTC6,  ADC(PTC6_ADC_NUM),  &ADC_CLOCK_REG(PTC6_ADC_NUM),  ADC_CLOCK_MASK(PTC6_ADC_NUM),  PTC6_ADC_CH};
const AnalogueIO analogueIO_PTC7        = {&digitalIO_PTC7,  ADC(PTC7_ADC_NUM),  &ADC_CLOCK_REG(PTC7_ADC_NUM),  ADC_CLOCK_MASK(PTC7_ADC_NUM),  PTC7_ADC_CH};
const AnalogueIO analogueIO_PTD4        = {&digitalIO_PTD4,  ADC(PTD4_ADC_NUM),  &ADC_CLOCK_REG(PTD4_ADC_NUM),  ADC_CLOCK_MASK(PTD4_ADC_NUM),  PTD4_ADC_CH};
const AnalogueIO analogueIO_PTD5        = {&digitalIO_PTD5,  ADC(PTD5_ADC_NUM),  &ADC_CLOCK_REG(PTD5_ADC_NUM),  ADC_CLOCK_MASK(PTD5_ADC_NUM),  PTD5_ADC_CH};
const AnalogueIO analogueIO_PTD6        = {&digitalIO_PTD6,  ADC(PTD6_ADC_NUM),  &ADC_CLOCK_REG(PTD6_ADC_NUM),  ADC_CLOCK_MASK(PTD6_ADC_NUM),  PTD6_ADC_CH};
const AnalogueIO analogueIO_PTE7        = {&digitalIO_PTE7,  ADC(PTE7_ADC_NUM),  &ADC_CLOCK_REG(PTE7_ADC_NUM),  ADC_CLOCK_MASK(PTE7_ADC_NUM),  PTE7_ADC_CH};
const AnalogueIO analogueIO_PTF0        = {&digitalIO_PTF0,  ADC(PTF0_ADC_NUM),  &ADC_CLOCK_REG(PTF0_ADC_NUM),  ADC_CLOCK_MASK(PTF0_ADC_NUM),  PTF0_ADC_CH};
const AnalogueIO analogueIO_PTF1        = {&digitalIO_PTF1,  ADC(PTF1_ADC_NUM),  &ADC_CLOCK_REG(PTF1_ADC_NUM),  ADC_CLOCK_MASK(PTF1_ADC_NUM),  PTF1_ADC_CH};
const AnalogueIO analogueIO_PTF2        = {&digitalIO_PTF2,  ADC(PTF2_ADC_NUM),  &ADC_CLOCK_REG(PTF2_ADC_NUM),  ADC_CLOCK_MASK(PTF2_ADC_NUM),  PTF2_ADC_CH};
const AnalogueIO analogueIO_PTG1        = {&digitalIO_PTG1,  ADC(PTG1_ADC_NUM),  &ADC_CLOCK_REG(PTG1_ADC_NUM),  ADC_CLOCK_MASK(PTG1_ADC_NUM),  PTG1_ADC_CH};
const AnalogueIO analogueIO_PTG2        = {&digitalIO_PTG2,  ADC(PTG2_ADC_NUM),  &ADC_CLOCK_REG(PTG2_ADC_NUM),  ADC_CLOCK_MASK(PTG2_ADC_NUM),  PTG2_ADC_CH};
