/**
 * @file lpspi.cpp (180.ARM_Peripherals/Sources/lpspi.cpp)
 * @brief LPI2C Code
 *
 * @version  V4.12.1.80
 * @date     13 April 2016
 */
#include "lpspi.h"

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
namespace USBDM {

} // End namespace USBDM
